server:
  port: 8090
  session-timeout: 60

security.basic.enabled: false
endpoints.shutdown.enabled: true

spring:
  profiles.active: dev

---
spring:
  profiles: dev

  jpa:
    showSql: true
    dataBase: H2
    hibernate.generateDdl: true

backend:
  admin:
    username: backendadmin
    password: betuzo
    backend.admin.role: BACKEND_ADMIN

entuliga.web.pathPhoto: /Users/betuzo/opt/photo/

---
spring:
  profiles: prepro

  jpa:
    showSql: false
    dataBase: POSTGRESQL
    hibernate.generateDdl: false

  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://ec2-54-225-199-108.compute-1.amazonaws.com:5432/d2s0bat8nnmlr7?sslmode=require
    username: lvqqialdspisrm
    password: lt2X_hajbja1u4RqkJbj4VgfX8

backend:
  admin:
    username: backendadmin
    password: betuzo
    backend.admin.role: BACKEND_ADMIN

entuliga.web.pathPhoto: /home/betuzo/opt/boot/prod/photo/