alter sequence colonia_id_seq restart with 1001;
INSERT INTO COLONIA (ID, NOMBRE, MUNICIPIO_ID) VALUES (1, 'El Bondho', 1);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (2, 'Oriental Knight''s-spur', 2);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (3, 'Resin Birch', 3);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (4, 'Inyo Meadow Lupine', 4);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (5, 'Variable Orange Lichen', 5);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (6, 'Tetrodontium Moss', 6);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (7, 'Aerialroot Bristle Fern', 7);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (8, 'Twobristle Rockdaisy', 8);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (9, 'Fendler''s Flatsedge', 9);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (10, 'Sierra Horkelia', 10);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (11, 'Howell''s Biscuitroot', 11);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (12, 'Switchgrass', 12);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (13, 'Cercidospora Lichen', 13);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (14, 'Moss Fern', 14);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (15, 'Biscayne Pricklyash', 15);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (16, 'Alena', 16);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (17, 'Giant Blue Eyed Mary', 17);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (18, 'Booth''s Willow', 18);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (19, 'Dwarf Eelgrass', 19);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (20, 'Fox Sedge', 20);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (21, 'Purpleflower Honeysuckle', 21);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (22, 'Ambiguous Aloina Moss', 22);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (23, 'Narrowpoint Knotweed', 23);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (24, 'Bodywood', 24);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (25, 'Golden Tickseed', 25);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (26, 'Cliff Fern', 26);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (27, 'Hulten''s Crabseye Lichen', 27);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (28, 'Smallspore Map Lichen', 28);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (29, 'Smallcane', 29);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (30, 'Valley Ringstem', 30);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (31, 'Intermountain Indian Breadroot', 31);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (32, 'Tumblegrass', 32);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (33, 'Corn', 33);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (34, 'Brewer''s Monardella', 34);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (35, 'Platygyrium Moss', 35);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (36, 'Rim Lichen', 36);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (37, 'Morningglory', 37);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (38, 'Tall Hawkweed', 38);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (39, 'Soft Heliotrope', 39);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (40, 'Spanish Lady', 40);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (41, 'Yolla Bolly Bedstraw', 41);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (42, 'Canada Lettuce', 42);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (43, 'Mt. Diablo Buckwheat', 43);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (44, 'Kanewsk''s Cup Lichen', 44);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (45, 'Brewer''s Lupine', 45);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (46, 'Venegasia', 46);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (47, 'Culebrita Island Water-willow', 47);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (48, 'Johnston''s Buckwheat', 48);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (49, 'Florida False Sunflower', 49);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (50, 'Engelmann Spruce', 50);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (51, 'Rusby''s Locust', 51);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (52, 'Chenille Pricklypear', 52);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (53, 'Herb Of The Cross', 53);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (54, 'Wart Lichen', 54);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (55, 'Colorado Tansyaster', 55);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (56, 'Woolly Locoweed', 56);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (57, 'Siskiyou Milkvetch', 57);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (58, 'Broadtooth Monkeyflower', 58);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (59, 'Palustriella Moss', 59);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (60, 'Red Canyon Beardtongue', 60);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (61, 'Texas Almond', 61);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (62, 'Sweetscent', 62);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (63, 'Bollean Mistletoe', 63);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (64, 'Bigelow''s Beggarticks', 64);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (65, 'Sphagnum', 65);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (66, 'Twisted Airplant', 66);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (67, 'Smallhead Doll''s Daisy', 67);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (68, 'Chile Cocopalm', 68);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (69, 'Bruneau Mariposa Lily', 69);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (70, 'Pitseed Goosefoot', 70);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (71, 'Lemmon''s Lupine', 71);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (72, 'Payson''s Draba', 72);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (73, 'Disc Lichen', 73);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (74, 'Cerro La Torrecilla Stopper', 74);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (75, 'Prism Bouchea', 75);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (76, 'Oldmaid Hawthorn', 76);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (77, 'Uhaloa', 77);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (78, 'Chalk Dudleya', 78);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (79, 'Cuyamaca Raspberry', 79);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (80, 'Alpine Bearberry', 80);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (81, 'Western Stoneseed', 81);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (82, 'Yellow Coralbells', 82);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (83, 'Horsetail', 83);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (84, 'Garden Huckleberry', 84);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (85, 'Leafy Pondweed', 85);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (86, 'Apache Plant', 86);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (87, 'Engelmann''s Knotweed', 87);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (88, 'Heartleaf Buttercup', 88);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (89, 'New Mexico Beeblossom', 89);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (90, 'Florida Mudmidget', 90);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (91, 'Nardoo', 91);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (92, 'Cutgrass', 92);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (93, 'Longleaf Woodoats', 93);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (94, 'Hairy Milkweed', 94);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (95, 'Calico Aster', 95);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (96, 'Straggling St. Johnswort', 96);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (97, 'Lindley''s Butterflybush', 97);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (98, 'Pilgrim Grape', 98);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (99, 'Young''s Snowbell', 99);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (100, 'Hammock Snakeroot', 100);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (101, 'Puerto Rico Purslane', 101);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (102, 'Rushpea', 102);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (103, 'Plumeless Thistle', 103);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (104, 'Royal Star Orchid', 104);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (105, 'Kings River Monkeyflower', 105);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (106, 'Honolulu Nehe', 106);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (107, 'Santa Cruz Island Manzanita', 107);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (108, 'Longleaf False Goldeneye', 108);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (109, 'Hybrid Oak', 109);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (110, 'Cooke''s Phacelia', 110);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (111, 'Blackish Locoweed', 111);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (112, 'Graphina Lichen', 112);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (113, 'Leavenworth''s Eryngo', 113);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (114, 'Swampwort', 114);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (115, 'Neckera Moss', 115);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (116, 'Drummond''s Beeblossom', 116);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (117, 'Threeseeded Sedge', 117);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (118, 'Low Serviceberry', 118);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (119, 'Jacquinia', 119);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (120, 'Pipewort', 120);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (121, 'Brewer''s Bittercress', 121);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (122, 'Mountain Pepperweed', 122);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (123, 'Shieldplant', 123);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (124, 'Red Rosemallow', 124);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (125, 'Common Mare''s-tail', 125);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (126, 'Almendrillo', 126);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (127, 'Winter Vetch', 127);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (128, 'Coastal Sand Sedge', 128);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (129, 'Coville Ceanothus', 129);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (130, 'Lanceleaf Ragweed', 130);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (131, 'Kellogg''s Sedge', 131);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (132, 'Big Chickweed', 132);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (133, 'Smooth Beggartick', 133);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (134, 'Tortured Chalice Lichen', 134);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (135, 'Hoover''s Manzanita', 135);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (136, 'Northern-rockcress', 136);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (137, 'Common Sneezeweed', 137);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (138, 'Howell''s Violet', 138);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (139, 'Marsh Valerian', 139);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (140, 'Southwestern Pricklypoppy', 140);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (141, 'Ruby Mountain Buckwheat', 141);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (142, 'Greene''s Popcornflower', 142);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (143, 'Flameflower', 143);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (144, 'Viereck''s Winged Rockcress', 144);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (145, 'Molokai Cyrtandra', 145);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (146, 'Ledge Stonecrop', 146);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (147, 'Indian Mallow', 147);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (148, 'Iwatsukiella Moss', 148);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (149, 'Common Pepperweed', 149);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (150, 'Strawberryleaf Cinquefoil', 150);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (151, 'Jacob''s-ladder', 151);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (152, 'Aaron''s Beard', 152);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (153, 'Plumed Jewelflower', 153);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (154, 'Pugnacious Blackberry', 154);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (155, 'Date Palm', 155);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (156, 'Mountain Saucerflower', 156);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (157, 'Whorled-leaf False Buttonweed', 157);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (158, 'Bryum Moss', 158);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (159, 'Ball Saltbush', 159);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (160, 'Raynolds'' Sedge', 160);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (161, 'West Indian Shrubverbena', 161);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (162, 'Patagonian Cypress', 162);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (163, 'Snailwood', 163);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (164, 'Rio Abajo Maiden Fern', 164);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (165, 'Desert Valley Fishhook Cactus', 165);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (166, 'California Grass Of Parnassus', 166);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (167, 'Halfchaff Sedge', 167);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (168, 'Puaokama', 168);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (169, 'Spiny Phlox', 169);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (170, 'Bluntlobe Cliff Fern', 170);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (171, 'Beebalm', 171);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (172, 'Bayberry', 172);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (173, 'Tampa Blackberry', 173);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (174, 'Bidwell''s Knotweed', 174);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (175, 'Woodland Sage', 175);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (176, 'Cream Avens', 176);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (177, 'Wire Mousetail', 177);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (178, 'Hybrid Ladyslipper', 178);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (179, 'Dot Lichen', 179);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (180, 'Thurber''s Buckwheat', 180);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (181, 'Geyer''s Twinpod', 181);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (182, 'King Bladderpod', 182);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (183, 'Coastal Flatsedge', 183);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (184, 'Proliferating Bulrush', 184);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (185, 'Vasey''s Coastal Pricklypear', 185);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (186, 'Valley Oak', 186);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (187, 'Mountain Mock Vervain', 187);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (188, 'Pyrenopsis Lichen', 188);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (189, 'Silver Twinpod', 189);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (190, 'Bellwort', 190);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (191, 'Dixie Iris', 191);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (192, 'Maxon''s Cloak Fern', 192);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (193, 'Shrimpplant', 193);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (194, 'Showy Penstemon', 194);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (195, 'Texas Muhly', 195);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (196, 'Kiwi', 196);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (197, 'Dwarf Coastweed', 197);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (198, 'Pine Valley Penstemon', 198);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (199, 'Yellow Penstemon', 199);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (200, 'Ethiopian Pepper', 200);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (201, 'Arctic Cottongrass', 201);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (202, 'African Basil', 202);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (203, 'Syrian-privet', 203);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (204, 'Meyen''s Flatsedge', 204);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (205, 'Norway Sedge', 205);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (206, 'Thunberg''s Geranium', 206);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (207, 'Barbados Cherry', 207);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (208, 'Ochna', 208);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (209, 'Indian Tobacco', 209);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (210, 'Blanketflower', 210);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (211, 'Cataract Physma Lichen', 211);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (212, 'White Edge Sedge', 212);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (213, 'Cherangani Clover', 213);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (214, 'Bristlecup Sandmat', 214);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (215, 'Graceful Fern', 215);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (216, 'Carolina Violet', 216);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (217, 'Tangled Starviolet', 217);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (218, 'Desert Bird''s-beak', 218);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (219, 'Bolander''s Mule-ears', 219);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (220, 'Wild Crapemyrtle', 220);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (221, 'Rough Desertparsley', 221);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (222, 'Sweetwilliam', 222);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (223, 'Pride Of Ohio', 223);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (224, 'Irish Potato', 224);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (225, 'Hoary Basil', 225);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (226, 'Dropseed', 226);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (227, 'Blood-red Pricklypear', 227);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (228, 'Pride Of Ohio', 228);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (229, 'Hollyleaf Gilia', 229);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (230, 'Rigid Navel Lichen', 230);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (231, 'Lecidea Lichen', 231);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (232, 'Plantain Goldenweed', 232);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (233, 'Florida Bully', 233);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (234, 'Yukon Hawkweed', 234);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (235, 'Fullstem', 235);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (236, 'Behring''s Rim Lichen', 236);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (237, 'Limestone Beardtongue', 237);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (238, 'Two-color Orange Lichen', 238);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (239, 'Broadleaf Milkvetch', 239);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (240, 'Dewflower', 240);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (241, 'Germander Meadowsweet', 241);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (242, 'Woodland Islandmint', 242);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (243, 'Wolf Lichen', 243);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (244, 'California Adderstongue', 244);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (245, 'Disc Lichen', 245);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (246, 'Bolander''s Phacelia', 246);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (247, 'True Forget-me-not', 247);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (248, 'Swamp Smartweed', 248);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (249, 'Lion''s Heart', 249);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (250, 'Columbian Lewisia', 250);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (251, 'Glades Spikerush', 251);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (252, 'Streamside Swordfern', 252);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (253, 'Pine-leaf Bottlebrush', 253);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (254, 'Evergreen Rose', 254);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (255, 'Crater Lichen', 255);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (256, 'Oconee Bells', 256);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (257, 'Refractohilum Lichen', 257);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (258, 'Broadbeard Beardtongue', 258);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (259, 'Cyrtandra', 259);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (260, 'Reindeer Lichen', 260);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (261, 'Siberian Sea Thrift', 261);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (262, 'Small Pondweed', 262);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (263, 'Bladderfern', 263);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (264, 'Trichothelium Lichen', 264);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (265, 'San Luis Lupine', 265);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (266, 'Ghiesbreght''s Panicgrass', 266);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (267, 'Fly Orchid', 267);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (268, 'Bill Williams Mountain Giant Hyssop', 268);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (269, 'Herzogiella Moss', 269);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (270, 'Candle Snuffer Moss', 270);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (271, 'Entodon Moss', 271);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (272, 'Tarweed', 272);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (273, 'Ozark Sedge', 273);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (274, 'Bread And Cheese', 274);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (275, 'Lens Pod Milkvetch', 275);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (276, 'San Andres Mountain Foxtail Cactus', 276);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (277, 'Slender Hop Clover', 277);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (278, 'Chapman''s Spurge', 278);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (279, 'Carolina Alumroot', 279);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (280, 'Canadian Blacksnakeroot', 280);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (281, 'Digitgrass', 281);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (282, 'Dwarf Checkerbloom', 282);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (283, 'Monardella', 283);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (284, 'Florida Sunflower', 284);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (285, 'Parodia', 285);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (286, 'Desert Wild Grape', 286);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (287, 'Jamaican Broom', 287);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (288, 'Eatonella', 288);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (289, 'Marshweed', 289);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (290, 'Marvel Of Peru', 290);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (291, 'Jones'' Townsend Daisy', 291);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (292, 'Groovestem Indian Plantain', 292);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (293, 'Heath Woodrush', 293);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (294, 'Bryum Moss', 294);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (295, 'Tailed Grapefern', 295);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (296, 'Cuban Tree Destroyer', 296);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (297, 'Stewardson''s Stopper', 297);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (298, 'Black Bamboo', 298);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (299, 'Oriental Mangrove', 299);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (300, 'Makole', 300);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (301, 'Sandmat Manzanita', 301);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (302, 'Scots Pine', 302);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (303, 'Fringed Lichen', 303);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (304, 'Hard Treefern', 304);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (305, 'Red Sierra Onion', 305);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (306, 'Bottlebrush Bulrush', 306);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (307, 'Sainfoin', 307);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (308, 'Willow Dock', 308);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (309, 'Foolproofplant', 309);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (310, 'Parlin''s Pussytoes', 310);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (311, 'Riverbank Vervain', 311);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (312, 'Sharptooth Blacksnakeroot', 312);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (313, 'Wright''s Spurge', 313);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (314, 'Harrison''s Barberry', 314);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (315, 'Mammoth Wildrye', 315);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (316, 'Northern Biscuitroot', 316);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (317, 'California Tortula Moss', 317);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (318, 'Solidstem Burnet Saxifrage', 318);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (319, 'Cyrtandra', 319);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (320, 'Curtis'' Spurge', 320);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (321, 'Obtuseleaf Scleropodium Moss', 321);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (322, 'Glass Mountain Rockdaisy', 322);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (323, 'Fragrant Cryptantha', 323);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (324, 'Philonotis Moss', 324);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (325, 'Cedar Gladecress', 325);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (326, 'Basalt Fleabane', 326);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (327, 'Lanai Colicwood', 327);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (328, 'Ash Meadows Blazingstar', 328);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (329, 'Cerulean Flaxlily', 329);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (330, 'Manatee Beaksedge', 330);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (331, 'Uluhe', 331);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (332, 'Northern St. Johnswort', 332);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (333, 'Longleaf Arnica', 333);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (334, 'Indianhemp', 334);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (335, 'Camptotheca', 335);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (336, 'Paintedtongue', 336);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (337, 'Scotch Broom', 337);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (338, 'Nippon Daisy', 338);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (339, 'Wingfruit Suncup', 339);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (340, 'Abey Amarillo', 340);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (341, 'Whitebristle Cottongrass', 341);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (342, 'Counterclockwise Nipple Cactus', 342);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (343, 'Elongated Mustard', 343);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (344, 'Didymodon Moss', 344);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (345, 'Guatemalan Gamagrass', 345);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (346, 'Tuber Starwort', 346);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (347, 'Violet Milkwort', 347);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (348, 'Purple Sage', 348);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (349, 'Wiry Snapdragon', 349);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (350, 'Victory Onion', 350);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (351, 'Bugle Hedgenettle', 351);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (352, 'Emperor Crowngrass', 352);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (353, 'Mossgrass', 353);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (354, 'Coastal Bluff Beggarticks', 354);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (355, 'Threelobe Rosemallow', 355);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (356, 'Spreading Groundsmoke', 356);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (357, 'Columbia Gorge Rockcress', 357);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (358, 'Escorzonera', 358);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (359, 'Pitcherplant', 359);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (360, 'Dammar Pine', 360);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (361, 'Fewflowered Spikerush', 361);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (362, 'West Indian Chinchweed', 362);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (363, 'Austrian Yellowcress', 363);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (364, 'Longleaf Pine', 364);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (365, 'Pennsylvania Sedge', 365);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (366, 'Cooley''s Bundleflower', 366);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (367, 'Pop Saltbush', 367);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (368, 'Stebbins'' Lewisia', 368);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (369, 'Rock Ragwort', 369);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (370, 'Fringed Rosemallow', 370);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (371, 'Largeflower Skeletonplant', 371);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (372, 'Browneyed Susan', 372);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (373, 'Butterfly Milkweed', 373);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (374, 'Boehmer''s Cat''s-tail', 374);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (375, 'Annual Wildrice', 375);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (376, 'Palmer''s Catchfly', 376);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (377, 'Piedmont Threeawn', 377);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (378, 'Colorado Rinodina Lichen', 378);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (379, 'Texas Cupflower', 379);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (380, 'Coastal Sand Verbena', 380);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (381, 'Rusty Foxglove', 381);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (382, 'Globethistle', 382);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (383, 'Leucophysalis', 383);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (384, 'Depressed Ipomopsis', 384);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (385, 'Bryoerythrophyllum Moss', 385);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (386, 'Phoenicaulis', 386);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (387, 'Jesuit''s Bark', 387);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (388, 'Mountain Blue Penstemon', 388);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (389, 'Bottlebrush Buckeye', 389);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (390, 'Yellowseed False Pimpernel', 390);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (391, 'Kern Cinquefoil', 391);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (392, 'Saintedwood', 392);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (393, 'Dwarf Dwarf-cudweed', 393);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (394, 'Ochna', 394);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (395, 'Pitted Onion', 395);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (396, 'Menzies'' Schiedea', 396);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (397, 'Redsepal Evening Primrose', 397);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (398, 'Harlequin Annual Lupine', 398);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (399, 'Common Blue Wood Aster', 399);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (400, 'Carolina Scalystem', 400);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (401, 'Douglas'' Buckwheat', 401);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (402, 'Smooth Teatree', 402);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (403, 'Canarygrass', 403);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (404, 'Fringed Amaranth', 404);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (405, 'Creeping Spleenwort', 405);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (406, 'Goldenrain Tree', 406);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (407, 'Tobacco Root', 407);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (408, 'Lindley''s Silverpuffs', 408);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (409, 'Greene''s Goldenbush', 409);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (410, 'Roundseed Panicgrass', 410);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (411, 'New Jersey Tea', 411);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (412, 'Franklin Spiderlily', 412);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (413, 'Howell''s Bentgrass', 413);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (414, 'Snow Lichen', 414);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (415, 'Walker Prairie Clover', 415);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (416, 'Seaside Knotweed', 416);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (417, 'Commelina', 417);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (418, 'Torrey''s Monkeyflower', 418);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (419, 'Lung Lichen', 419);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (420, 'Monte Neva Indian Paintbrush', 420);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (421, 'Baltzell''s Sedge', 421);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (422, 'Orange Lichen', 422);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (423, 'Dwarf Hackberry', 423);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (424, 'Noble Fir', 424);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (425, 'Rattan''s Monkeyflower', 425);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (426, 'Dwarf Willowherb', 426);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (427, 'Horsehair Lichen', 427);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (428, 'Crabseye', 428);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (429, 'Miraculous Berry', 429);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (430, 'Monongahela Barbara''s Buttons', 430);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (431, 'Blue Finger', 431);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (432, 'Uralanguis', 432);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (433, 'New Mexico Phacelia', 433);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (434, 'Dill Daisy', 434);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (435, 'Jaumea', 435);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (436, 'Whitesnow', 436);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (437, 'Dogwoodleaf', 437);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (438, 'Texas Wildrice', 438);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (439, 'Virginia Pinweed', 439);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (440, 'Pennsylvania Hawthorn', 440);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (441, 'Wyoming Townsend Daisy', 441);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (442, 'Lehua ''ahihi', 442);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (443, 'Para Cress', 443);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (444, 'Tortula Moss', 444);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (445, 'Granular Trapeliopsis Lichen', 445);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (446, 'Argentine Evening Primrose', 446);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (447, 'Bolander''s Onion', 447);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (448, 'Small Tumbleweed Mustard', 448);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (449, 'Labrador Cup Lichen', 449);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (450, 'Twogrooved Milkvetch', 450);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (451, 'Jepson''s Woolly Sunflower', 451);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (452, 'Douglas-fir Dwarf Mistletoe', 452);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (453, 'Berg''s Panicgrass', 453);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (454, 'Idaho Bladderpod', 454);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (455, 'Parry''s Sedge', 455);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (456, 'Thesium', 456);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (457, 'Roughpod Bladderpod', 457);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (458, 'White Cinquefoil', 458);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (459, 'Longstalk Cranesbill', 459);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (460, 'Spreading Gooseberry', 460);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (461, 'Rayless Goldenrod', 461);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (462, 'Corrigiola', 462);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (463, 'Douglas'' Silverpuffs', 463);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (464, 'Snow Lichen', 464);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (465, 'Dwarf Plantain', 465);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (466, 'Golden Columbine', 466);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (467, 'Jayuya', 467);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (468, 'Roundleaf Thoroughwort', 468);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (469, 'Shrubby Woodsorrel', 469);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (470, 'Pink Plains Beardtongue', 470);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (471, 'One-nerved Ernodea', 471);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (472, 'Palo De Hierro', 472);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (473, 'Sharpleaf Valerian', 473);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (474, 'Redwood Insideout Flower', 474);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (475, 'Argentina Mountain Bamboo', 475);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (476, 'White Rosemallow', 476);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (477, 'American Smoketree', 477);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (478, 'Rogers Pass Bladderpod', 478);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (479, 'Devilwood', 479);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (480, 'Black Henbane', 480);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (481, 'San Benito Fritillary', 481);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (482, 'Radiola', 482);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (483, 'Lodgepole Lupine', 483);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (484, 'Cordgrass', 484);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (485, 'Coastal Hedgenettle', 485);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (486, 'Parry Manzanita', 486);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (487, 'Prairie Sandreed', 487);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (488, 'Japanese Bush Cherry', 488);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (489, 'California Fescue', 489);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (490, 'Landolphia Rubber', 490);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (491, 'Laurel Clockvine', 491);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (492, 'Henderson''s Wavewing', 492);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (493, 'Cyphomeris', 493);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (494, 'Arizona Siltbush', 494);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (495, 'Sanddune Ipomopsis', 495);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (496, 'Rothrock''s Keckiella', 496);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (497, 'Rimmed Lichen', 497);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (498, 'Winecup Clarkia', 498);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (499, 'Pale Indian Paintbrush', 499);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (500, 'Mecca Myrrh', 500);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (501, 'Purple Meadowparsnip', 501);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (502, 'Rainlily', 502);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (503, 'Canyon Mock Orange', 503);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (504, 'Hairy Fimbry', 504);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (505, 'Uinta Basin Stickleaf', 505);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (506, 'Star Apple', 506);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (507, 'Saltbush', 507);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (508, 'Matted Lichen', 508);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (509, 'Mt. Rainier Lousewort', 509);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (510, 'Desert Frasera', 510);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (511, 'Sonoita Nightshade', 511);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (512, 'Dwarf Huckleberry', 512);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (513, 'Rosary Babybonnets', 513);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (514, 'Northern Orange Lichen', 514);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (515, 'Zion Milkvetch', 515);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (516, 'Morro Manzanita', 516);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (517, 'White Rosewood', 517);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (518, 'Sonoran Oak', 518);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (519, 'Low Pussytoes', 519);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (520, 'Herb Sophia', 520);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (521, 'Chiggery Grapes', 521);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (522, 'Sugar Sumac', 522);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (523, 'Klamath Mountain Mahogany', 523);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (524, 'Starfern', 524);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (525, 'Tall Ragwort', 525);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (526, 'Blue Boneset', 526);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (527, 'Oregon Ash', 527);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (528, 'Australian Water-clover', 528);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (529, 'Sleeping Popcornflower', 529);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (530, 'Sunset Crater Beardtongue', 530);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (531, 'Lichenostigma Lichen', 531);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (532, 'Blazing Star', 532);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (533, 'Arar Tree', 533);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (534, 'Blue Finger', 534);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (535, 'Yam', 535);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (536, 'Chinese Foldwing', 536);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (537, 'Claspingleaf St. Johnswort', 537);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (538, 'Maize', 538);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (539, 'Modoc Gilia', 539);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (540, 'Inland Bluegrass', 540);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (541, 'Beach Moonflower', 541);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (542, 'Aerialroot Bristle Fern', 542);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (543, 'Jayuya', 543);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (544, 'Mount Shasta Jacob''s-ladder', 544);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (545, 'Syrian Acanthus', 545);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (546, 'Mousesear', 546);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (547, 'Dixie Sandmat', 547);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (548, 'Homalium', 548);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (549, 'Florida Pineland Spurge', 549);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (550, 'Dwarf Hackberry', 550);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (551, 'Spike Lichen', 551);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (552, 'Thin-wall Quillwort', 552);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (553, 'Heller''s Grape', 553);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (554, 'Japanese Skimmia', 554);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (555, 'Rand''s Goldenrod', 555);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (556, 'Oval-leaf Blueberry', 556);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (557, 'Cuero De Sapo', 557);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (558, 'Jack In The Pulpit', 558);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (559, 'Hairy Canary-clover', 559);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (560, 'Reclining Bulrush', 560);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (561, 'Vicksburg Blackberry', 561);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (562, 'Cerro Hawthorn', 562);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (563, 'Lands Of Papa Pritchardia', 563);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (564, 'Shieldplant', 564);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (565, 'Yam', 565);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (566, 'Keyflower', 566);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (567, 'Heartleaf Speedwell', 567);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (568, 'Cleland''s Evening Primrose', 568);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (569, 'Rock Goldenrod', 569);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (570, 'Mauna Kea Dubautia', 570);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (571, 'Marsh Rose Gentian', 571);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (572, 'Moth Combseed', 572);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (573, 'Spreading Leastdaisy', 573);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (574, 'Roughleaf Aster', 574);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (575, 'Padre''s Shootingstar', 575);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (576, 'Giant Angelica', 576);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (577, 'Proliferating Bulrush', 577);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (578, 'Slender-leaf Sandwort', 578);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (579, 'Sand Fleabane', 579);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (580, 'Desertstar', 580);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (581, 'Arizona Bristlegrass', 581);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (582, 'Robinson''s Onion', 582);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (583, 'Desert Willow', 583);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (584, 'Zigzag Groundsmoke', 584);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (585, 'Clustered Green Gentian', 585);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (586, 'Cup Lichen', 586);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (587, 'Scouler''s Popcornflower', 587);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (588, 'Traveler''s-joy', 588);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (589, 'Yosemite Rockcress', 589);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (590, 'Crownvetch', 590);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (591, 'Rowell''s Groundcherry', 591);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (592, 'Labrador Tea', 592);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (593, 'Hiddenflower Phacelia', 593);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (594, 'Kombe Arrow Poison', 594);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (595, 'Hollyfern', 595);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (596, 'Cushion Draba', 596);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (597, 'Mesa Verde Stickseed', 597);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (598, 'Shining Clubmoss', 598);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (599, 'Birdeye Primrose', 599);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (600, 'Volantines Preciosos', 600);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (601, 'Jeweled Tonguefern', 601);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (602, 'Hybrid Violet', 602);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (603, 'Salt Sandspurry', 603);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (604, 'Liverwort Monkeyflower', 604);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (605, 'Razor Grass', 605);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (606, 'Eucalyptus', 606);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (607, 'Turtleback', 607);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (608, 'Wild Cassia', 608);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (609, 'Broadleaf Maidenhair', 609);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (610, 'Beach Spiderlily', 610);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (611, 'Orange Cotoneaster', 611);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (612, 'Texosporium Lichen', 612);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (613, 'Lagetta', 613);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (614, 'Stoneroot', 614);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (615, 'Meiwa Kumquat', 615);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (616, 'Chamisso Arnica', 616);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (617, 'Lemmon''s Beggarticks', 617);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (618, 'Purple Meadowparsnip', 618);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (619, 'Maricao River Hempvine', 619);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (620, 'Curvepod Fumewort', 620);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (621, 'Nodding Onion', 621);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (622, 'Pincushions', 622);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (623, 'Micrandra', 623);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (624, 'Mcnab''s Cypress', 624);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (625, 'Mountain Pepperweed', 625);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (626, 'Gumbo Milkvetch', 626);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (627, 'Alpine Lovage', 627);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (628, 'Sphagnum', 628);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (629, 'Delta Bulrush', 629);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (630, 'Arrowhead Maiden Fern', 630);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (631, 'Orris-root', 631);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (632, 'Black Coral-pea', 632);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (633, 'Mountain Lupine', 633);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (634, 'Melanelia Lichen', 634);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (635, 'American False Pennyroyal', 635);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (636, 'Stiffstem Flax', 636);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (637, 'Longanther Rush', 637);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (638, 'Mesa Spikemoss', 638);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (639, 'Albizia', 639);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (640, 'Plume Poppy', 640);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (641, 'Palmer Oak', 641);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (642, 'Santa Cruz Wallflower', 642);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (643, 'Russian Milkvetch', 643);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (644, 'Southern Bog Clubmoss', 644);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (645, 'Eastern Bottlebrush Grass', 645);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (646, 'Rusby''s Goldenbush', 646);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (647, 'Red Star-thistle', 647);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (648, 'Providence Mountain Milkvetch', 648);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (649, 'Silver Tussock', 649);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (650, 'Oak Creek Triteleia', 650);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (651, 'Hillyhock', 651);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (652, 'Western False Dragonhead', 652);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (653, 'Blackseed Sandspurry', 653);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (654, 'Cleft Sedge', 654);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (655, 'Dot Lichen', 655);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (656, 'Mountain Spleenwort', 656);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (657, 'Caucasus Catmint', 657);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (658, 'Yellow Butterfly Palm', 658);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (659, 'Coastal Plain Heliotrope', 659);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (660, 'Kadjatoa', 660);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (661, 'Rough Cocklebur', 661);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (662, 'Wooton''s Ragwort', 662);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (663, 'Barneby''s Clover', 663);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (664, 'Eastern Wahoo', 664);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (665, 'Western Rough Goldenrod', 665);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (666, 'European Frostweed', 666);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (667, 'Zwackhiomyces Lichen', 667);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (668, 'True Forget-me-not', 668);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (669, 'Orange Lichen', 669);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (670, 'Pacific Fishscale Lichen', 670);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (671, 'Spiny Cliffbrake', 671);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (672, 'Jepson''s Broomrape', 672);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (673, 'Wool Grass', 673);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (674, 'Gila Thistle', 674);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (675, 'Webber Needlegrass', 675);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (676, 'Creeping Maiden Fern', 676);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (677, 'False Spotted St. Johnswort', 677);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (678, 'Palm Beachbells', 678);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (679, 'Shasta Lily', 679);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (680, 'Nigaki', 680);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (681, 'Menzies'' Campion', 681);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (682, 'Eureka Dunegrass', 682);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (683, 'Antlerfern', 683);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (684, 'Fairy Slipper', 684);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (685, 'Smallflower Hawksbeard', 685);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (686, 'Rock Buckwheat', 686);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (687, 'Purple Milkwort', 687);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (688, 'Dichelyma Moss', 688);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (689, 'Narrowfruit Braya', 689);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (690, 'Arizona Passionflower', 690);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (691, 'Brassia', 691);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (692, 'Guadalupe Fescue', 692);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (693, 'Stern''s Medlar', 693);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (694, 'Plantainleaf Halberd Fern', 694);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (695, 'Lecania Lichen', 695);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (696, 'Star Tickseed', 696);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (697, 'Scarlet Gilia', 697);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (698, 'Hulten''s Crabseye Lichen', 698);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (699, 'Seaside Juniper', 699);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (700, 'Parmotrema Lichen', 700);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (701, 'Pacific Mistletoe', 701);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (702, 'Longstalk Sedge', 702);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (703, 'Thurber''s Sedge', 703);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (704, 'Ha''a', 704);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (705, 'Kealia Cyanea', 705);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (706, 'Fireweed', 706);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (707, 'Spleenwort', 707);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (708, 'Green Muhly', 708);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (709, 'African Violet', 709);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (710, 'Panicum', 710);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (711, 'Arizona Willow', 711);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (712, 'Idaho Biscuitroot', 712);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (713, 'Common Spring-gold', 713);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (714, 'Syrian Mustard', 714);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (715, 'Disc Lichen', 715);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (716, 'Bramble Acacia', 716);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (717, 'Partridge Pea', 717);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (718, 'Kenmore''s Porocyphus Lichen', 718);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (719, 'Narrowleaf Suncup', 719);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (720, 'Clove Phlox', 720);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (721, 'Prostrate Knotweed', 721);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (722, 'Rocky Mountain Indian Parsley', 722);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (723, 'Oxyspora', 723);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (724, 'Forked Nailwort', 724);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (725, 'Mielichhof''s Copper Moss', 725);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (726, 'Frost''s Dirinaria Lichen', 726);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (727, 'Tall Tonguefern', 727);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (728, 'Indian Lettuce', 728);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (729, 'Jade Plant', 729);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (730, 'Ernest''s Spiderwort', 730);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (731, 'Russet Buffaloberry', 731);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (732, 'Spotted Medick', 732);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (733, 'Black Papillaria Moss', 733);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (734, 'Woodland Lettuce', 734);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (735, 'Arrowleaf Falsepickerelweed', 735);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (736, 'Fineleaf Hymenopappus', 736);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (737, 'Mosquito Bulrush', 737);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (738, 'Paiute Suncup', 738);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (739, 'Chalice Vine', 739);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (740, 'Boreal Catchfly', 740);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (741, 'Lophophora', 741);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (742, 'Cochise Dodder', 742);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (743, 'Purple Crowberry', 743);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (744, 'Neofuscelia Lichen', 744);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (745, 'Fescue Ryegrass', 745);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (746, 'Na Pali-kona Woodfern', 746);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (747, 'Lands Of Papa Pritchardia', 747);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (748, 'Abrams'' Liveforever', 748);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (749, 'False Beardgrass', 749);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (750, 'Blue Dwarf Fleabane', 750);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (751, 'Fewleaf Spiderflower', 751);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (752, 'Wild Flag', 752);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (753, 'Slimstalk Spiderling', 753);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (754, 'Texas Western Daisy', 754);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (755, 'Bessey''s Locoweed', 755);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (756, 'Northeastern Dewberry', 756);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (757, 'El Yunque Colorado', 757);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (758, 'Olympic Brachydontium Moss', 758);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (759, 'Panamint Springparsley', 759);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (760, 'Tropical Sage', 760);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (761, 'False Sesame', 761);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (762, 'Lesser Saltmarsh Sedge', 762);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (763, 'Narrowleaf Bedstraw', 763);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (764, 'Virginia Goldenrod', 764);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (765, 'Prairie Spiderwort', 765);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (766, 'Mousetail', 766);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (767, 'Glandleaf Milkwort', 767);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (768, 'Wild Cucumber', 768);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (769, 'Rough Bedstraw', 769);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (770, 'Bering Chickweed', 770);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (771, 'Streambank Flowering Fern', 771);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (772, 'Erwin''s Red Turtlehead', 772);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (773, 'Lobb''s Fiddleleaf', 773);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (774, 'Desert Savior', 774);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (775, 'Fringed Orchid', 775);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (776, 'Longbract Pohlia Moss', 776);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (777, 'Slenderleaf False Foxglove', 777);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (778, 'San Diego Spineflower', 778);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (779, 'Cypress-knee Helmet Orchid', 779);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (780, 'Nevada Milkvetch', 780);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (781, 'Catillaria Lichen', 781);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (782, 'Wild Sweetwilliam', 782);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (783, 'Oldpasture Bluegrass', 783);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (784, 'Purple Meadowparsnip', 784);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (785, 'Rattan''s Monkeyflower', 785);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (786, 'European Turkey Oak', 786);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (787, 'Sarea Lichen', 787);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (788, 'Sclerophyton Lichen', 788);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (789, 'Commerson''s Nightshade', 789);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (790, 'Dot Lichen', 790);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (791, 'Bilobed Grewia', 791);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (792, 'Earleaf Greenbrier', 792);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (793, 'Dwarf Violet Iris', 793);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (794, 'Sevier Milkvetch', 794);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (795, 'Coastal Cosmopolitan Bulrush', 795);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (796, 'Milkweed', 796);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (797, 'Largeleaf Lupine', 797);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (798, 'Hedgemustard', 798);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (799, 'Rocky Mountain Elder', 799);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (800, 'Climbing Bedstraw', 800);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (801, 'Abrams'' Liveforever', 801);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (802, 'Creeping Snowberry', 802);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (803, 'Bambarra Groundnut', 803);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (804, 'Rabbit-tobacco', 804);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (805, 'Sarcographa Lichen', 805);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (806, 'Shield Nasturtium', 806);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (807, 'Brownseed Paspalum', 807);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (808, 'Cetraria Lichen', 808);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (809, 'Armeria', 809);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (810, 'White Thoroughwort', 810);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (811, 'Purple Meadowparsnip', 811);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (812, 'Great Globethistle', 812);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (813, 'Trachycystis Moss', 813);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (814, 'Merrill''s Beard Lichen', 814);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (815, 'Coenogonium Lichen', 815);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (816, 'Map Lichen', 816);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (817, 'Perezia', 817);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (818, 'Sawtooth Sunflower', 818);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (819, 'Macleaya', 819);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (820, 'Neneleau', 820);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (821, 'Largeleaf Rose Gentian', 821);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (822, 'Dwarf Clover', 822);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (823, 'Giant Red Indian Paintbrush', 823);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (824, 'Curvedleaf Stonecrop', 824);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (825, 'Stickystem Penstemon', 825);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (826, 'Mistassini Primrose', 826);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (827, 'Cutleaf Blackberry', 827);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (828, 'Drepanocladus Moss', 828);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (829, 'Yellow Pincushion', 829);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (830, 'Mullein', 830);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (831, 'Swordleaf Blue-eyed Grass', 831);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (832, 'Forked Nightshade', 832);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (833, 'Brittle Lichen', 833);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (834, 'Rue Spleenwort', 834);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (835, 'Helmet Flower', 835);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (836, 'Mespilus', 836);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (837, 'Nissenan Manzanita', 837);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (838, 'Undergreen Willow', 838);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (839, 'Turkish Baby''s-breath', 839);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (840, 'Wart Lichen', 840);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (841, 'Guyanese Pepper', 841);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (842, 'Kauai Phyllostegia', 842);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (843, 'Myelochroa Lichen', 843);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (844, 'Basindaisy', 844);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (845, 'Phillips'' Cliff Fern', 845);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (846, 'Island False Bindweed', 846);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (847, 'Oahu Pilo Kea', 847);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (848, 'Dot Lichen', 848);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (849, 'Magnolia', 849);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (850, 'Common Wheat', 850);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (851, 'Mouseear Hawkweed', 851);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (852, 'Bashful Bulrush', 852);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (853, 'Broccoli', 853);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (854, 'Skirret', 854);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (855, 'Desert Lovegrass', 855);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (856, 'Fire Pink', 856);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (857, 'Bittercress', 857);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (858, 'New England Justiceweed', 858);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (859, 'Galax', 859);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (860, 'Virginia Mountainmint', 860);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (861, 'Bingen Lupine', 861);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (862, 'Spleenwort', 862);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (863, 'Lemhi Halimolobos', 863);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (864, 'Pride-of-barbados', 864);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (865, 'Beet', 865);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (866, 'Goatweed', 866);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (867, 'Orcutt''s Bristleweed', 867);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (868, 'Desert Baccharis', 868);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (869, 'Woolly Cottonflower', 869);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (870, 'Rhodes Grass', 870);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (871, 'Whorled Marshpennywort', 871);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (872, 'Stalked Fleabane', 872);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (873, 'Hall''s Orthotrichum Moss', 873);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (874, 'Pickering''s Reedgrass', 874);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (875, 'Screwbean Mesquite', 875);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (876, 'Brittle Lichen', 876);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (877, 'Hairy Mock Orange', 877);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (878, 'Las Vegas Tumblemustard', 878);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (879, 'Pygmydaisy', 879);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (880, 'Puakauhi', 880);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (881, 'Largeleaf Rose Gentian', 881);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (882, 'Eyebane', 882);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (883, 'Shrubland Dubautia', 883);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (884, 'Cows Clover', 884);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (885, 'Maui Cyanea', 885);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (886, 'Cup Orchid', 886);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (887, 'Dog''s-tongue', 887);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (888, 'Velvet Tree', 888);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (889, 'False Agoseris', 889);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (890, 'Fuzzyleaf Clover', 890);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (891, 'Tapertip Dodder', 891);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (892, 'Halberdleaf Tearthumb', 892);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (893, 'Maule''s Quince', 893);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (894, 'Spreading Navarretia', 894);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (895, 'White Logwood', 895);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (896, 'Arizona Blanketflower', 896);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (897, 'Arroyo Fameflower', 897);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (898, 'Seacliff Tetramolopium', 898);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (899, 'Cayenne Porterweed', 899);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (900, 'Sweet Pitcherplant', 900);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (901, 'Matted Lupine', 901);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (902, 'Northern Needleleaf', 902);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (903, 'Saltlover', 903);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (904, 'Jamaican Caper', 904);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (905, 'Tetraphis Moss', 905);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (906, 'Heliotrope', 906);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (907, 'White Thoroughwort', 907);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (908, 'Spurge', 908);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (909, 'Jamaican Caper', 909);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (910, 'Laurera Lichen', 910);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (911, 'Jovibarba', 911);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (912, 'Drepanocladus Moss', 912);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (913, 'Kopa', 913);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (914, 'Mosquito Bills', 914);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (915, 'Zizotes Milkweed', 915);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (916, 'Barwood', 916);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (917, 'Yellow Nightshade Groundcherry', 917);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (918, 'Orthotrichum Moss', 918);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (919, 'Nepalese Browntop', 919);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (920, 'Miriquidica Lichen', 920);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (921, 'Douglas'' Stitchwort', 921);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (922, 'Fivefinger Chickensage', 922);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (923, 'Snake River Phlox', 923);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (924, 'Heldreich''s Clover', 924);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (925, 'Tundra Aster', 925);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (926, 'Acevedo''s Velvetshrub', 926);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (927, 'Flavoparmelia Lichen', 927);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (928, 'Bog Lobelia', 928);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (929, 'Crandall''s Beardtongue', 929);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (930, 'Hollyleaf Clover', 930);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (931, 'Virginia Jointvetch', 931);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (932, 'Smallhead Aster', 932);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (933, 'South Texas Prairie Clover', 933);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (934, 'Prairienymph', 934);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (935, 'Small Enchanter''s Nightshade', 935);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (936, 'Ross'' Avens', 936);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (937, 'Melocactus', 937);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (938, 'Roundleaf Waterlily', 938);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (939, 'Nuttall''s Yellowcress', 939);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (940, 'Nasturtium', 940);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (941, 'Keahi', 941);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (942, 'Rosewood', 942);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (943, 'Canyon Liveforever', 943);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (944, 'Coastal Bluff Beggarticks', 944);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (945, 'Gigantochloa', 945);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (946, 'Smooth Northern-rockcress', 946);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (947, 'Silver Beardgrass', 947);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (948, 'Brewer''s Rockcress', 948);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (949, 'White Cypress-pine', 949);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (950, 'Hygrohypnum Moss', 950);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (951, 'Bigflower Pawpaw', 951);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (952, 'Maricao Lidflower', 952);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (953, 'Yellow Columbine', 953);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (954, 'Drummond''s Dropseed', 954);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (955, 'Orange Lichen', 955);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (956, 'European Feather Grass', 956);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (957, 'Long-stolon Sedge', 957);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (958, 'Cone-cup Spikerush', 958);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (959, 'Blueberry', 959);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (960, 'Canada Cocklebur', 960);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (961, 'Goosefoot Violet', 961);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (962, 'Gray''s Biscuitroot', 962);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (963, 'Ozark Dropseed', 963);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (964, 'Spike Trisetum', 964);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (965, 'Stinkingfish', 965);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (966, 'Flatseed Sandmat', 966);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (967, 'Disc Lichen', 967);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (968, 'Threeleaf Soapberry', 968);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (969, 'American Pokeweed', 969);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (970, 'Lavender Sage', 970);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (971, 'Imshaugia Lichen', 971);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (972, 'Bottle-palm', 972);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (973, 'Ptychomitrium Moss', 973);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (974, 'Nodding Bluegrass', 974);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (975, 'Slender Hop Clover', 975);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (976, 'Leatherstem', 976);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (977, 'White Ballmustard', 977);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (978, 'Pink Fuzzybean', 978);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (979, 'Blunt Chaff Flower', 979);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (980, 'European Plum', 980);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (981, 'Rhodes Grass', 981);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (982, 'Pyxine Lichen', 982);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (983, 'Bruised Lichen', 983);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (984, 'Swordleaf Blue-eyed Grass', 984);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (985, 'Tiburon Mariposa Lily', 985);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (986, 'Narrowleaf Arnica', 986);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (987, 'Hairy-seed Goldenrod', 987);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (988, 'California Saltbush', 988);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (989, 'Greenvein Lady''s Tresses', 989);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (990, 'Conejo Buckwheat', 990);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (991, 'Eggplant', 991);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (992, 'Thread Rush', 992);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (993, 'Arthothelium Lichen', 993);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (994, 'Henry''s Spiderlily', 994);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (995, 'Philadelphia Fleabane', 995);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (996, 'Lewis River Suncup', 996);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (997, 'Pacific Alpine Wormwood', 997);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (998, 'Harsh Indian Paintbrush', 998);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (999, 'Island Grapefern', 999);
insert into COLONIA (ID, NOMBRE, MUNICIPIO_ID) values (1000, 'Artillery Plant', 1000);
