
INSERT INTO ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) VALUES (1, 'Hidalgo', 'HGO', 1);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (2, 'Sihanoukville', 'KH', 2);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (3, 'Omboué', 'GA', 3);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (4, 'Krasni Okny', 'UA', 4);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (5, 'San Nicolás', 'HN', 5);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (6, 'Peskovka', 'RU', 6);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (7, 'Nakatsu', 'JP', 7);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (8, 'Minien East', 'PH', 8);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (9, 'Pil’na', 'RU', 9);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (10, 'Gulou', 'CN', 10);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (11, 'Sinchao', 'PE', 11);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (12, 'Igrim', 'RU', 12);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (13, 'Chedao', 'CN', 13);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (14, 'Ngilengan', 'ID', 14);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (15, 'Vila Chã', 'PT', 15);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (16, 'Fenoarivo Be', 'MG', 16);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (17, 'Genova', 'IT', 17);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (18, 'Zhuting', 'CN', 18);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (19, 'Tocota', 'PE', 19);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (20, 'Kopong', 'BW', 20);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (21, 'Borlänge', 'SE', 21);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (22, 'Guayatá', 'CO', 22);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (23, 'Jiebu', 'CN', 23);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (24, 'Tangal', 'PH', 24);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (25, 'Loga', 'ID', 25);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (26, 'Aranyaprathet', 'TH', 26);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (27, 'Zhavoronki', 'RU', 27);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (28, 'Georgīevka', 'KZ', 28);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (29, 'Al Manşūrah', 'EG', 29);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (30, 'Huaguo', 'CN', 30);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (31, 'Onsala', 'SE', 31);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (32, 'Mangere', 'NZ', 32);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (33, 'Sukth', 'AL', 33);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (34, 'Ciseda', 'ID', 34);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (35, 'Lianovérgi', 'GR', 35);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (36, 'Siqiao', 'CN', 36);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (37, 'Vysokovsk', 'RU', 37);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (38, 'Malekān', 'IR', 38);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (39, 'Stockholm', 'SE', 39);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (40, 'Plaza Huincul', 'AR', 40);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (41, 'Guararema', 'BR', 41);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (42, 'Juru', 'BR', 42);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (43, 'Kurumkan', 'RU', 43);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (44, 'Charlotte', 'US', 44);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (45, 'Rentian', 'CN', 45);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (46, 'Shemursha', 'RU', 46);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (47, 'Geshan', 'CN', 47);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (48, 'Kristiansand S', 'NO', 48);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (49, 'Ramat HaSharon', 'IL', 49);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (50, 'Regnów', 'PL', 50);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (51, 'Bonsari', 'ID', 51);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (52, 'Lavaur', 'FR', 52);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (53, 'Matriz de Camaragibe', 'BR', 53);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (54, 'Krajan', 'ID', 54);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (55, 'Cijayana', 'ID', 55);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (56, 'São Bernardo do Campo', 'BR', 56);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (57, 'Baun', 'ID', 57);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (58, 'Paraíba do Sul', 'BR', 58);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (59, 'Zhuangbian', 'CN', 59);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (60, 'Usol’ye', 'RU', 60);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (61, 'Kambing', 'PH', 61);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (62, 'Taizhou', 'CN', 62);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (63, 'Gaoshi', 'CN', 63);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (64, 'Hedong', 'CN', 64);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (65, 'Zumarraga', 'PH', 65);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (66, 'Domampot', 'PH', 66);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (67, 'Malasugui', 'PH', 67);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (68, 'Zambujeira do Mar', 'PT', 68);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (69, 'Stanisław Dolny', 'PL', 69);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (70, 'Saray', 'AZ', 70);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (71, 'Jhang Sadr', 'PK', 71);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (72, 'Löddeköpinge', 'SE', 72);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (73, 'Guagua', 'PH', 73);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (74, 'Ishigaki', 'JP', 74);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (75, 'Midões', 'PT', 75);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (76, 'Quebradas', 'PT', 76);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (77, 'Liloan', 'PH', 77);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (78, 'Paris 06', 'FR', 78);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (79, 'San Diego', 'US', 79);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (80, 'Gálvez', 'AR', 80);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (81, 'Krynki', 'PL', 81);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (82, 'Keffin Hausa', 'NG', 82);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (83, 'Ganping', 'CN', 83);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (84, 'Magaozhuang', 'CN', 84);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (85, 'Fāmenīn', 'IR', 85);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (86, 'Ngluweng Dua', 'ID', 86);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (87, 'Dungloe', 'IE', 87);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (88, 'Oetuke', 'ID', 88);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (89, 'Chiquinquirá', 'CO', 89);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (90, 'Buje', 'HR', 90);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (91, 'Apóstoles', 'AR', 91);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (92, 'Dongtucheng', 'CN', 92);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (93, 'Saint-Étienne-du-Rouvray', 'FR', 93);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (94, 'Ganyesa', 'ZA', 94);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (95, 'Sapiranga', 'BR', 95);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (96, 'Sidi Amar', 'MA', 96);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (97, 'Mazamet', 'FR', 97);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (98, 'Wahang Dua', 'ID', 98);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (99, 'Lokoja', 'NG', 99);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (100, 'Ludvika', 'SE', 100);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (101, 'Shencun', 'CN', 101);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (102, 'Sherbrooke', 'CA', 102);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (103, 'Rudna Mała', 'PL', 103);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (104, 'Pinayagan Norte', 'PH', 104);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (105, 'Shimen', 'CN', 105);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (106, 'Pointe Michel', 'DM', 106);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (107, 'Kinalaglagan', 'PH', 107);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (108, 'Stockholm', 'SE', 108);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (109, 'Chapecó', 'BR', 109);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (110, 'Wan’an', 'CN', 110);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (111, 'Shengao', 'CN', 111);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (112, 'Maronge', 'ID', 112);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (113, 'Shadili', 'CN', 113);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (114, 'Dziemiany', 'PL', 114);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (115, 'Ban Lam Luk Ka', 'TH', 115);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (116, 'Namwala', 'ZM', 116);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (117, 'Québec', 'CA', 117);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (118, 'Portel', 'PT', 118);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (119, 'Xianghuaqiao', 'CN', 119);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (120, 'Örebro', 'SE', 120);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (121, 'Asyūţ', 'EG', 121);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (122, 'Falun', 'SE', 122);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (123, 'Sovetskoye', 'RU', 123);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (124, 'Replot', 'FI', 124);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (125, 'Xianyang', 'CN', 125);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (126, 'Taen Tengah', 'ID', 126);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (127, 'Tempe', 'US', 127);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (128, 'Lhasa', 'CN', 128);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (129, 'Ithari', 'NP', 129);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (130, 'Krasnogorskoye', 'RU', 130);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (131, 'Carpalho', 'PT', 131);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (132, 'Angkup', 'ID', 132);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (133, 'Rehoboth', 'NA', 133);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (134, 'Krajan Tegalombo', 'ID', 134);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (135, 'Fonte de Angeão', 'PT', 135);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (136, 'Pailiao', 'CN', 136);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (137, 'Renfrew', 'CA', 137);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (138, 'Gojō', 'JP', 138);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (139, 'N’dalatando', 'AO', 139);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (140, 'Vallentuna', 'SE', 140);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (141, 'Suphan Buri', 'TH', 141);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (142, 'Gandu', 'BR', 142);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (143, 'Padamulya', 'ID', 143);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (144, 'Igarassu', 'BR', 144);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (145, 'Tuodian', 'CN', 145);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (146, 'Kristiansand S', 'NO', 146);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (147, 'Hisings Kärra', 'SE', 147);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (148, 'Teodoro Sampaio', 'BR', 148);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (149, 'Tortosa', 'PH', 149);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (150, 'Yŏng-dong', 'KR', 150);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (151, 'Oeba', 'ID', 151);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (152, 'Saint-Raymond', 'CA', 152);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (153, 'Bozhou', 'CN', 153);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (154, 'Rukaj', 'AL', 154);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (155, 'Mohale’s Hoek', 'LS', 155);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (156, 'Palmerston North', 'NZ', 156);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (157, 'Mondoteko', 'ID', 157);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (158, 'Peranap', 'ID', 158);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (159, 'Outeiro', 'PT', 159);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (160, 'Zográfos', 'GR', 160);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (161, 'General Pinedo', 'AR', 161);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (162, 'Timurjaya', 'ID', 162);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (163, 'Komsomol’sk', 'RU', 163);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (164, 'Rasskazovo', 'RU', 164);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (165, 'Kuala Bintang', 'ID', 165);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (166, 'Patos', 'BR', 166);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (167, 'Fratar', 'AL', 167);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (168, 'Pelileo', 'EC', 168);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (169, 'Campoverde', 'PE', 169);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (170, 'La Quebrada', 'VE', 170);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (171, 'Gālīkesh', 'IR', 171);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (172, 'Jatinagara', 'ID', 172);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (173, 'Kolor', 'ID', 173);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (174, 'Plakhtiyivka', 'UA', 174);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (175, 'Repentigny', 'CA', 175);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (176, 'Pervomaysk', 'RU', 176);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (177, 'Jabłonka', 'PL', 177);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (178, 'El Gouna', 'EG', 178);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (179, 'Vapnyarka', 'UA', 179);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (180, 'Atlanta', 'US', 180);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (181, 'Legen', 'SI', 181);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (182, 'Jiangxigou', 'CN', 182);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (183, 'Cauayan', 'PH', 183);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (184, 'Guatraché', 'AR', 184);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (185, 'Jiangtian', 'CN', 185);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (186, 'Huangascar', 'PE', 186);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (187, 'Chigasaki', 'JP', 187);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (188, 'Nzeto', 'AO', 188);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (189, 'Pancas', 'BR', 189);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (190, 'Arrah', 'CI', 190);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (191, 'Gobernador Costa', 'AR', 191);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (192, 'Zharkent', 'KZ', 192);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (193, 'Balauring', 'ID', 193);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (194, 'Melbourne', 'US', 194);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (195, 'Cergy-Pontoise', 'FR', 195);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (196, 'Kedungwaru', 'ID', 196);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (197, 'Siguiri', 'GN', 197);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (198, 'Södra Sandby', 'SE', 198);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (199, 'Sarykemer', 'KZ', 199);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (200, 'Porta', 'PT', 200);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (201, 'Jiangjing', 'CN', 201);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (202, 'Metsovo', 'GR', 202);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (203, 'Helie', 'CN', 203);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (204, 'Tunasbaru', 'ID', 204);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (205, 'Nikolayevskaya', 'RU', 205);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (206, 'Pyongyang', 'KP', 206);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (207, 'Taipingchuan', 'CN', 207);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (208, 'Padangsidempuan', 'ID', 208);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (209, 'Prakhon Chai', 'TH', 209);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (210, 'Taibai', 'CN', 210);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (211, 'Xingfu', 'CN', 211);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (212, 'Lahuaytambo', 'PE', 212);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (213, 'Viga', 'PH', 213);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (214, 'Kota Bharu', 'MY', 214);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (215, 'Longhua', 'CN', 215);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (216, 'Tuscaloosa', 'US', 216);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (217, 'Le Tampon', 'RE', 217);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (218, 'Steinkjer', 'NO', 218);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (219, 'Mali Iđoš', 'RS', 219);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (220, 'Bereeda', 'SO', 220);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (221, 'Chikwawa', 'MW', 221);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (222, 'Chenfangji', 'CN', 222);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (223, 'Shifo', 'CN', 223);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (224, 'Myślenice', 'PL', 224);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (225, 'Jivia', 'PE', 225);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (226, 'Bolszewo', 'PL', 226);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (227, 'Zhaxirabdain', 'CN', 227);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (228, 'Karak', 'PK', 228);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (229, 'Zhushan', 'CN', 229);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (230, 'Aulnay-sous-Bois', 'FR', 230);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (231, 'Bajiao', 'CN', 231);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (232, 'Blobo', 'ID', 232);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (233, 'Nedryhayliv', 'UA', 233);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (234, 'Englewood', 'US', 234);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (235, 'Vanadzor', 'AM', 235);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (236, 'Capiíbary', 'PY', 236);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (237, 'Mogocha', 'RU', 237);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (238, 'Alikalia', 'SL', 238);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (239, 'Mishima', 'JP', 239);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (240, 'Amboise', 'FR', 240);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (241, 'As Saffānīyah', 'SA', 241);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (242, 'Baota', 'CN', 242);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (243, 'Michałowo', 'PL', 243);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (244, 'Energodar', 'UA', 244);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (245, 'Coayllo', 'PE', 245);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (246, 'Port Barton', 'PH', 246);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (247, 'Loandjili', 'CG', 247);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (248, 'Aldeia da Piedade', 'PT', 248);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (249, 'Maevatanana', 'MG', 249);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (250, 'Pirojpur', 'BD', 250);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (251, 'Maukaro', 'ID', 251);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (252, 'Daping', 'CN', 252);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (253, 'Perzów', 'PL', 253);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (254, 'Santa Magdalena', 'PH', 254);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (255, 'Geyuan', 'CN', 255);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (256, 'Changyuan', 'CN', 256);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (257, 'Esperança', 'BR', 257);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (258, 'Świnice Warckie', 'PL', 258);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (259, 'Karangtengah Lor', 'ID', 259);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (260, 'Kitāf', 'YE', 260);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (261, 'Ilha Solteira', 'BR', 261);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (262, 'Seia', 'PT', 262);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (263, 'Hulu', 'CN', 263);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (264, 'Dushan', 'CN', 264);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (265, 'Novo Selo', 'BG', 265);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (266, 'Had Kourt', 'MA', 266);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (267, 'Santa Rosa de Lima', 'SV', 267);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (268, 'Guarda Nova', 'PT', 268);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (269, 'Castañas', 'PH', 269);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (270, 'Jimsar', 'CN', 270);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (271, 'Rawasan', 'ID', 271);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (272, 'Conceição da Feira', 'BR', 272);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (273, 'Andir', 'ID', 273);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (274, 'Pangligaran', 'ID', 274);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (275, 'Jājarm', 'IR', 275);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (276, 'Tawa', 'CN', 276);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (277, 'Liujiachang', 'CN', 277);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (278, 'Chengzhong', 'CN', 278);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (279, 'Mauá', 'BR', 279);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (280, 'Panimbang', 'ID', 280);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (281, 'Mardakyany', 'AZ', 281);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (282, 'Richmond', 'ZA', 282);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (283, 'Dashiren', 'CN', 283);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (284, 'Goiatuba', 'BR', 284);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (285, 'Dobratice', 'CZ', 285);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (286, 'La Cruz', 'MX', 286);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (287, 'Nuoxizhi', 'CN', 287);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (288, 'Yuen Long Kau Hui', 'HK', 288);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (289, 'Vide', 'PT', 289);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (290, 'Shanglaxiu', 'CN', 290);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (291, 'Piggs Peak', 'SZ', 291);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (292, 'Thanh Khê', 'VN', 292);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (293, 'Shelopugino', 'RU', 293);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (294, 'Pedro Leopoldo', 'BR', 294);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (295, 'Loučná nad Desnou', 'CZ', 295);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (296, 'Bayan Bulag', 'CN', 296);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (297, 'Andovoranto', 'MG', 297);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (298, 'Pantian', 'CN', 298);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (299, 'Groningen', 'NL', 299);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (300, 'Michurinskoye', 'RU', 300);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (301, 'Xiaxihao', 'CN', 301);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (302, 'El Sombrero', 'VE', 302);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (303, 'Mórrope', 'PE', 303);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (304, 'Liucun', 'CN', 304);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (305, 'Lulindi', 'TZ', 305);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (306, 'Nueva Esperanza', 'MX', 306);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (307, 'Dongchuan', 'CN', 307);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (308, 'Lingkou', 'CN', 308);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (309, 'Pipa', 'CN', 309);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (310, 'Punta de Bombón', 'PE', 310);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (311, 'Sammatti', 'FI', 311);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (312, 'Caijiazha', 'CN', 312);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (313, 'Lebao', 'ID', 313);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (314, 'Kapuan', 'ID', 314);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (315, 'Waoundé', 'SN', 315);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (316, 'Berat', 'AL', 316);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (317, 'Turze Pole', 'PL', 317);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (318, 'As Salţ', 'JO', 318);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (319, 'Vila Chã', 'PT', 319);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (320, 'Pomacocha', 'PE', 320);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (321, 'Sahatsakhan', 'TH', 321);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (322, 'Capanema', 'BR', 322);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (323, 'Gradačac', 'BA', 323);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (324, 'Tupã', 'BR', 324);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (325, 'Tucurú', 'GT', 325);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (326, 'Liushikou', 'CN', 326);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (327, 'Barrī ash Sharqī', 'SY', 327);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (328, 'Taoyuan', 'CN', 328);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (329, 'Lyon', 'FR', 329);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (330, 'Singgit', 'ID', 330);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (331, 'Xujiafang', 'CN', 331);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (332, 'Jednorożec', 'PL', 332);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (333, 'Perovo', 'RU', 333);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (334, 'Vaitape', 'PF', 334);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (335, 'Reykjanesbær', 'IS', 335);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (336, 'Shuiji', 'CN', 336);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (337, 'Xinqiaohe', 'CN', 337);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (338, 'Irecê', 'BR', 338);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (339, 'Chavão', 'PT', 339);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (340, 'Yingkeng', 'CN', 340);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (341, 'Sandao', 'CN', 341);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (342, 'Utajärvi', 'FI', 342);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (343, 'A’yi Take', 'CN', 343);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (344, 'Ülken', 'KZ', 344);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (345, 'Urshel’skiy', 'RU', 345);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (346, 'Iporã', 'BR', 346);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (347, 'Tombu', 'SL', 347);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (348, 'Ponong', 'PH', 348);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (349, 'Trélissac', 'FR', 349);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (350, 'Tadou', 'CN', 350);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (351, 'Gorno Orizari', 'MK', 351);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (352, 'Altamira', 'BR', 352);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (353, 'Ayapel', 'CO', 353);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (354, 'Ribeirópolis', 'BR', 354);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (355, 'Port-au-Prince', 'HT', 355);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (356, 'Shuangzhu', 'CN', 356);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (357, 'Hakha', 'MM', 357);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (358, 'Zelmeņi', 'LV', 358);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (359, 'Poitiers', 'FR', 359);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (360, 'Kushiro', 'JP', 360);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (361, 'Maomiaoji', 'CN', 361);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (362, 'Vsetín', 'CZ', 362);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (363, 'Terjan', 'ID', 363);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (364, 'Kallithéa', 'GR', 364);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (365, 'Peddie', 'ZA', 365);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (366, 'Pelotas', 'BR', 366);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (367, 'Fort Smith', 'US', 367);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (368, 'Maiduguri', 'NG', 368);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (369, 'Carpalho', 'PT', 369);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (370, 'Montaneza', 'PH', 370);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (371, 'Welibo', 'ID', 371);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (372, 'Tecpán Guatemala', 'GT', 372);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (373, 'Dapo', 'CN', 373);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (374, 'Bagani', 'NA', 374);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (375, 'Lukovo', 'MK', 375);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (376, 'Muikamachi', 'JP', 376);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (377, 'Billère', 'FR', 377);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (378, 'A’ershan', 'CN', 378);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (379, 'Crossmolina', 'IE', 379);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (380, 'Saransk', 'RU', 380);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (381, 'Tegalheras', 'ID', 381);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (382, 'Cikarang', 'ID', 382);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (383, 'Elbasan', 'AL', 383);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (384, 'Vitória de Santo Antão', 'BR', 384);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (385, 'Tomorlog', 'CN', 385);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (386, 'Barra de São Francisco', 'BR', 386);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (387, 'Nglego', 'ID', 387);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (388, 'Shijiazhuang', 'CN', 388);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (389, 'Glad', 'PH', 389);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (390, 'Fajsławice', 'PL', 390);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (391, 'Saint Aubin', 'MU', 391);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (392, 'Yigo Village', 'GU', 392);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (393, 'Nikita', 'UA', 393);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (394, 'Carmen', 'PH', 394);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (395, 'Bjuv', 'SE', 395);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (396, 'Bueng Samakkhi', 'TH', 396);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (397, 'Santa Marta de Penaguião', 'PT', 397);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (398, 'Bissen', 'LU', 398);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (399, 'Eséka', 'CM', 399);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (400, 'Shibi', 'CN', 400);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (401, 'Ban Na Muang', 'TH', 401);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (402, 'Pedra Branca', 'BR', 402);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (403, 'Sukhobuzimskoye', 'RU', 403);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (404, 'Kulotino', 'RU', 404);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (405, 'Douz', 'TN', 405);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (406, 'Bordeaux', 'FR', 406);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (407, 'Kurbnesh', 'AL', 407);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (408, 'Dresden', 'DE', 408);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (409, 'Ishiki', 'JP', 409);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (410, 'Stockholm', 'SE', 410);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (411, 'Spasskoye', 'RU', 411);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (412, 'Houmt Souk', 'TN', 412);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (413, 'Mpongwe', 'ZM', 413);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (414, 'Svyatogorsk', 'UA', 414);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (415, 'Villanova', 'IT', 415);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (416, 'Casa Nova', 'PT', 416);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (417, 'Sanya', 'CN', 417);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (418, 'Volosovo', 'RU', 418);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (419, 'Potštát', 'CZ', 419);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (420, 'Paringin', 'ID', 420);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (421, 'Shangyuan', 'CN', 421);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (422, 'Porta', 'PT', 422);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (423, 'Willemstad', 'CW', 423);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (424, 'Stockholm', 'SE', 424);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (425, 'Detroit', 'US', 425);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (426, 'Győr', 'HU', 426);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (427, 'Bicurga', 'GQ', 427);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (428, 'Góra Kalwaria', 'PL', 428);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (429, 'Tuban', 'PH', 429);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (430, 'Nakhon Luang', 'TH', 430);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (431, 'Oliveiras', 'PT', 431);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (432, 'Cabannungan Second', 'PH', 432);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (433, 'Parabcan', 'PH', 433);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (434, 'Gbawe', 'GH', 434);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (435, 'Gachalá', 'CO', 435);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (436, 'Timaru', 'NZ', 436);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (437, 'Toyooka', 'JP', 437);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (438, 'Mulhouse', 'FR', 438);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (439, 'Qujiang', 'CN', 439);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (440, 'Berlin', 'DE', 440);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (441, 'Las Yaras', 'PE', 441);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (442, 'Frampol', 'PL', 442);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (443, 'Amuntai', 'ID', 443);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (444, 'Vichadero', 'UY', 444);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (445, 'Hongshanyao', 'CN', 445);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (446, 'Hausjärvi', 'FI', 446);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (447, 'Khon San', 'TH', 447);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (448, 'Zarechnyy', 'RU', 448);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (449, 'Santa Ana', 'PH', 449);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (450, 'Ritaebang', 'ID', 450);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (451, 'Bayt ‘Adhāqah', 'YE', 451);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (452, 'Niška Banja', 'RS', 452);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (453, 'Wushan', 'CN', 453);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (454, 'Santa Cruz', 'PE', 454);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (455, 'Ciasna', 'PL', 455);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (456, 'Shanhe', 'CN', 456);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (457, 'Uto', 'JP', 457);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (458, 'Kuching', 'MY', 458);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (459, 'Tabalong', 'PH', 459);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (460, 'Carthage', 'TN', 460);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (461, 'Alofi', 'NU', 461);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (462, 'Dolice', 'PL', 462);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (463, 'Damasak', 'NG', 463);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (464, 'Ngembel', 'ID', 464);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (465, 'Trollhättan', 'SE', 465);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (466, 'Lipinki Łużyckie', 'PL', 466);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (467, 'Medina Estates', 'GH', 467);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (468, 'Suponevo', 'RU', 468);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (469, 'Trollhättan', 'SE', 469);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (470, 'Senhor da Serra', 'PT', 470);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (471, 'Ystad', 'SE', 471);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (472, 'Manaloal', 'PH', 472);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (473, 'Stryszawa', 'PL', 473);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (474, 'Mawang', 'CN', 474);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (475, 'Viljakkala', 'FI', 475);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (476, 'Gouveia', 'PT', 476);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (477, 'Smolensk', 'RU', 477);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (478, 'Tangnanzhen', 'CN', 478);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (479, 'El Cocuy', 'CO', 479);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (480, 'Lexington', 'US', 480);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (481, 'New Orleans', 'US', 481);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (482, 'Guáimaro', 'CU', 482);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (483, 'Shuishi', 'CN', 483);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (484, 'Waitangi', 'NZ', 484);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (485, 'Mata', 'PT', 485);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (486, 'Oesena', 'ID', 486);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (487, 'New Cebu', 'PH', 487);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (488, 'Lębork', 'PL', 488);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (489, 'Warburton', 'PK', 489);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (490, 'Jiazhuang', 'CN', 490);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (491, 'Beishan', 'CN', 491);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (492, 'Santaluz', 'BR', 492);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (493, 'Düsseldorf', 'DE', 493);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (494, 'Saint-Leu-la-Forêt', 'FR', 494);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (495, 'Hamburg', 'DE', 495);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (496, 'Fukuyama', 'JP', 496);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (497, 'Alma', 'CA', 497);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (498, 'Rangpur', 'BD', 498);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (499, 'Cevicos', 'DO', 499);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (500, 'Hohoe', 'GH', 500);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (501, 'San Miguel Dueñas', 'GT', 501);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (502, 'Philadelphia', 'US', 502);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (503, 'Shimen', 'CN', 503);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (504, 'Wamba', 'CD', 504);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (505, 'Genang', 'ID', 505);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (506, 'Gudurica', 'RS', 506);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (507, 'Pécs', 'HU', 507);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (508, 'Khodzhi-Gasan', 'AZ', 508);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (509, 'Aheloy', 'BG', 509);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (510, 'Pesqueira', 'BR', 510);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (511, 'Shuanglu', 'CN', 511);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (512, 'Selkirk', 'CA', 512);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (513, 'Jingzhou', 'CN', 513);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (514, 'Panayagan', 'ID', 514);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (515, 'Shiniujiang', 'CN', 515);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (516, 'Muzi', 'CN', 516);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (517, 'Obernai', 'FR', 517);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (518, 'Itaberaba', 'BR', 518);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (519, 'Dolna Banjica', 'MK', 519);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (520, 'Kanugrahan', 'ID', 520);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (521, 'Konin', 'PL', 521);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (522, 'Eišiškės', 'LT', 522);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (523, 'Novokubansk', 'RU', 523);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (524, 'San Isidro', 'MX', 524);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (525, 'Khirdalan', 'AZ', 525);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (526, 'Itaberaba', 'BR', 526);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (527, 'Muara', 'ID', 527);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (528, 'Jabat', 'MH', 528);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (529, 'Soure', 'PT', 529);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (530, 'Leżajsk', 'PL', 530);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (531, 'Pinheiral', 'BR', 531);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (532, 'Šentilj v Slov. Goricah', 'SI', 532);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (533, 'Shancheng', 'CN', 533);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (534, 'Jardín', 'CO', 534);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (535, 'Toledo', 'BR', 535);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (536, 'Přimda', 'CZ', 536);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (537, 'Taishan', 'CN', 537);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (538, 'San Jacinto', 'PH', 538);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (539, 'Laguilayan', 'PH', 539);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (540, 'San José', 'CR', 540);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (541, 'Gjilan', 'XK', 541);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (542, 'Kladruby', 'CZ', 542);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (543, 'Boto', 'ID', 543);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (544, 'Al Khamīs', 'YE', 544);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (545, 'Prakhon Chai', 'TH', 545);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (546, 'Solna', 'SE', 546);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (547, 'Galovac', 'HR', 547);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (548, 'Schellenberg', 'LI', 548);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (549, 'Charata', 'AR', 549);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (550, 'Liucheng', 'CN', 550);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (551, 'Hongshunli', 'CN', 551);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (552, 'Partikan', 'ID', 552);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (553, 'Ipil', 'PH', 553);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (554, 'Villanova', 'IT', 554);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (555, 'Semypolky', 'UA', 555);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (556, 'Cigemlong', 'ID', 556);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (557, 'Mayskiy', 'RU', 557);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (558, 'Yangdun', 'CN', 558);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (559, 'Shebunino', 'RU', 559);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (560, 'Bābolsar', 'IR', 560);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (561, 'Labrang', 'CN', 561);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (562, 'Mariscala', 'UY', 562);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (563, 'Sardasht', 'IR', 563);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (564, 'Hova', 'SE', 564);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (565, 'Yanxi', 'CN', 565);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (566, 'Hengtanggang', 'CN', 566);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (567, 'Song’ao', 'CN', 567);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (568, 'Pereyaslav-Khmel’nyts’kyy', 'UA', 568);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (569, 'Desnogorsk', 'RU', 569);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (570, 'El Puente', 'HN', 570);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (571, 'Skövde', 'SE', 571);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (572, 'Prado', 'BR', 572);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (573, 'La Charité-sur-Loire', 'FR', 573);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (574, 'Santa Cruz do Capibaribe', 'BR', 574);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (575, 'Lages', 'PT', 575);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (576, 'Yuchi', 'CN', 576);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (577, 'Fosses', 'FR', 577);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (578, 'Kambing', 'PH', 578);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (579, 'Varpaisjärvi', 'FI', 579);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (580, 'Nizhniy Novgorod', 'RU', 580);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (581, 'Aībak', 'AF', 581);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (582, 'Taungoo', 'MM', 582);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (583, 'Al Maşdūr', 'TN', 583);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (584, 'Yecun', 'CN', 584);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (585, 'Taza', 'MA', 585);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (586, 'Akkol’', 'KZ', 586);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (587, 'Sagay', 'PH', 587);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (588, 'Zaragoza', 'PH', 588);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (589, 'Karangbenda', 'ID', 589);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (590, 'New Haven', 'US', 590);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (591, 'Levallois-Perret', 'FR', 591);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (592, 'Paôy Pêt', 'KH', 592);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (593, 'Sumeng', 'CN', 593);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (594, 'Chaupimarca', 'PE', 594);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (595, 'Rossosh’', 'RU', 595);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (596, 'Taoyuan', 'CN', 596);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (597, 'Goascorán', 'HN', 597);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (598, 'Qiucun', 'CN', 598);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (599, 'Chengbei', 'CN', 599);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (600, 'Sumberagung', 'ID', 600);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (601, 'Alistráti', 'GR', 601);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (602, 'Mont-Joli', 'CA', 602);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (603, 'Moravská Nová Ves', 'CZ', 603);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (604, 'San Juan Atitán', 'GT', 604);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (605, 'Xijiadian', 'CN', 605);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (606, 'Changshan', 'CN', 606);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (607, 'Dinājpur', 'BD', 607);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (608, 'Shuikou', 'CN', 608);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (609, 'Naili', 'PH', 609);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (610, 'Igcocolo', 'PH', 610);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (611, 'Guhua', 'CN', 611);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (612, 'Tofa', 'NG', 612);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (613, 'Roma', 'IT', 613);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (614, 'San Francisco', 'PH', 614);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (615, 'Montgomery', 'US', 615);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (616, 'Czernikowo', 'PL', 616);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (617, 'Gondar', 'ET', 617);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (618, 'Toila', 'EE', 618);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (619, 'Sambungjaya', 'ID', 619);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (620, 'Butel', 'MK', 620);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (621, 'Malaga', 'ES', 621);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (622, 'Ngajum', 'ID', 622);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (623, 'Columbus', 'US', 623);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (624, 'Šuto Orizare', 'MK', 624);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (625, 'Corpus Christi', 'US', 625);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (626, 'Itororó', 'BR', 626);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (627, 'Trinidad', 'UY', 627);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (628, 'Tomelilla', 'SE', 628);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (629, 'Piława Górna', 'PL', 629);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (630, 'Sidomulyo', 'ID', 630);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (631, 'Sobreira', 'PT', 631);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (632, 'Tafeng', 'CN', 632);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (633, 'Serra da Silveira', 'PT', 633);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (634, 'Solčava', 'SI', 634);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (635, 'Outlook', 'CA', 635);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (636, 'Poço Verde', 'BR', 636);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (637, 'Selorejo', 'ID', 637);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (638, 'San Isidro', 'PH', 638);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (639, 'Kandana', 'LK', 639);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (640, 'Bobowa', 'PL', 640);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (641, 'Jabon', 'ID', 641);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (642, 'Concord', 'CA', 642);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (643, 'Jambulang', 'ID', 643);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (644, 'Septfontaines', 'LU', 644);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (645, 'Wangzuizi', 'CN', 645);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (646, 'Maranganí', 'PE', 646);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (647, 'Siedliska', 'PL', 647);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (648, 'Denov', 'UZ', 648);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (649, 'Koryukivka', 'UA', 649);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (650, 'Buenavista', 'PH', 650);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (651, 'Ploemeur', 'FR', 651);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (652, 'Metz', 'FR', 652);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (653, 'Donggaocun', 'CN', 653);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (654, 'Issenye', 'TZ', 654);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (655, 'Yajiwa', 'NG', 655);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (656, 'Garcia Hernandez', 'PH', 656);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (657, 'Brooklyn', 'US', 657);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (658, 'Thị Trấn Yên Ninh', 'VN', 658);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (659, 'Huangcun', 'CN', 659);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (660, 'Barbacena', 'BR', 660);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (661, 'Catujal', 'PT', 661);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (662, 'Xiangshan', 'CN', 662);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (663, 'Luhyny', 'UA', 663);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (664, 'Suay', 'PH', 664);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (665, 'Västra Frölunda', 'SE', 665);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (666, 'Mesógi', 'CY', 666);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (667, 'Karaidel’', 'RU', 667);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (668, 'Shaba Zhen', 'CN', 668);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (669, 'Cahors', 'FR', 669);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (670, 'Villa Altagracia', 'DO', 670);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (671, 'Anaco', 'VE', 671);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (672, 'Shambu', 'ET', 672);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (673, 'Majan', 'ID', 673);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (674, 'Contagem', 'BR', 674);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (675, 'Tužno', 'HR', 675);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (676, 'Varjota', 'BR', 676);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (677, 'Pleshanovo', 'RU', 677);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (678, 'Santa Catalina', 'UY', 678);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (679, 'Bang Pa-in', 'TH', 679);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (680, 'Debark’', 'ET', 680);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (681, 'San Carlos', 'CO', 681);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (682, 'João Câmara', 'BR', 682);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (683, 'Podgórzyn', 'PL', 683);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (684, 'Shentong', 'CN', 684);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (685, 'Olofström', 'SE', 685);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (686, 'Xiabuji', 'CN', 686);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (687, 'Karangsari', 'ID', 687);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (688, 'Ciekek', 'ID', 688);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (689, 'Venda', 'PT', 689);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (690, 'Cartagena', 'CL', 690);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (691, 'Huangtukuang', 'CN', 691);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (692, 'Świnna', 'PL', 692);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (693, 'Celje', 'SI', 693);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (694, 'Sena', 'TH', 694);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (695, 'Kōchi-shi', 'JP', 695);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (696, 'Santiago del Torno', 'BO', 696);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (697, 'Atalaia', 'PT', 697);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (698, 'Cikananga', 'ID', 698);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (699, 'Pedregulho', 'BR', 699);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (700, 'Zhuangke', 'CN', 700);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (701, 'Łapanów', 'PL', 701);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (702, 'Bardalah', 'PS', 702);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (703, 'Bulungu', 'CD', 703);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (704, 'Salawu', 'ID', 704);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (705, 'Vágia', 'GR', 705);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (706, 'Nggambel', 'ID', 706);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (707, '‘Ayn al ‘Arab', 'SY', 707);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (708, 'Vlachovo Březí', 'CZ', 708);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (709, 'Alenquer', 'BR', 709);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (710, 'Rostokino', 'RU', 710);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (711, 'Burayevo', 'RU', 711);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (712, 'Miejska Górka', 'PL', 712);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (713, 'Fornos', 'PT', 713);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (714, 'Gufeng', 'CN', 714);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (715, 'Cintra', 'AR', 715);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (716, 'El Cobre', 'VE', 716);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (717, 'Conceição do Jacuípe', 'BR', 717);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (718, 'Bununu Dass', 'NG', 718);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (719, 'Liqiao', 'CN', 719);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (720, 'Serzedo', 'PT', 720);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (721, 'Manzil Bū Zalafah', 'TN', 721);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (722, 'Amgalang', 'CN', 722);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (723, 'Cadiz', 'ES', 723);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (724, 'Chociwel', 'PL', 724);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (725, 'Saint-Priest', 'FR', 725);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (726, 'Bayan Huxu', 'CN', 726);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (727, 'Alès', 'FR', 727);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (728, 'Staraya Mayna', 'RU', 728);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (729, 'Ouro Preto do Oeste', 'BR', 729);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (730, 'Cipicung', 'ID', 730);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (731, 'Ranambeling', 'ID', 731);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (732, 'Fuzihe', 'CN', 732);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (733, 'Muting', 'ID', 733);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (734, 'Tekstil’shchiki', 'RU', 734);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (735, 'Daqingshan', 'CN', 735);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (736, 'Zambujal', 'PT', 736);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (737, 'Askiz', 'RU', 737);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (738, 'Huallanca', 'PE', 738);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (739, 'Anhua', 'CN', 739);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (740, 'Pilar', 'PH', 740);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (741, 'Tan-Tan', 'MA', 741);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (742, 'Liulin', 'CN', 742);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (743, 'Jiancha', 'CN', 743);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (744, 'Zhong’an', 'CN', 744);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (745, 'Huazhaizi', 'CN', 745);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (746, 'Zielonki', 'PL', 746);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (747, 'Abū Mūsā', 'IR', 747);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (748, 'Maulawin', 'PH', 748);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (749, 'Velingrad', 'BG', 749);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (750, 'Český Těšín', 'CZ', 750);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (751, 'Ryczywół', 'PL', 751);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (752, 'Kuantan', 'MY', 752);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (753, 'Teófilo Otoni', 'BR', 753);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (754, 'Ifanadiana', 'MG', 754);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (755, 'Cirahab', 'ID', 755);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (756, 'Neskaupstaður', 'IS', 756);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (757, 'El Cairo', 'CO', 757);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (758, 'Pasvalys', 'LT', 758);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (759, 'Sarvaš', 'HR', 759);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (760, 'Dadamtu', 'CN', 760);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (761, 'Tungdor', 'CN', 761);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (762, 'Bunga Mas', 'ID', 762);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (763, 'Brétigny-sur-Orge', 'FR', 763);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (764, 'Qingtong', 'CN', 764);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (765, 'Cagwait', 'PH', 765);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (766, 'Teluk Pinang', 'ID', 766);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (767, 'Stare Juchy', 'PL', 767);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (768, 'Sułkowice', 'PL', 768);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (769, 'Adorjan', 'RS', 769);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (770, 'Tanjungluar', 'ID', 770);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (771, 'Churubamba', 'PE', 771);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (772, 'Khvastovichi', 'RU', 772);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (773, 'Fabianki', 'PL', 773);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (774, 'Xiaoshun', 'CN', 774);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (775, 'Santa Teresita', 'PH', 775);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (776, 'Vargön', 'SE', 776);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (777, 'Utena', 'LT', 777);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (778, 'Kisasa', 'TZ', 778);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (779, 'Houston', 'US', 779);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (780, 'Tisma', 'NI', 780);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (781, 'Nioro', 'ML', 781);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (782, 'Haruai', 'ID', 782);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (783, 'Horní Cerekev', 'CZ', 783);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (784, 'Donskoy', 'RU', 784);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (785, 'Huang’ao', 'CN', 785);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (786, 'Ninh Giang', 'VN', 786);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (787, 'Blois', 'FR', 787);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (788, 'Uchkeken', 'RU', 788);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (789, 'Prozor', 'BA', 789);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (790, 'Ketampak', 'ID', 790);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (791, 'Springfield', 'US', 791);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (792, 'Saue', 'EE', 792);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (793, 'Kertabumi', 'ID', 793);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (794, 'Bularit', 'PH', 794);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (795, 'Torsby', 'SE', 795);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (796, 'Melaka', 'MY', 796);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (797, 'Maricá', 'BR', 797);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (798, 'Teongtoda', 'ID', 798);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (799, 'Labrador City', 'CA', 799);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (800, 'Loureiro', 'PT', 800);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (801, 'Quillo', 'PE', 801);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (802, 'Novyy Urgal', 'RU', 802);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (803, 'Severnyy', 'RU', 803);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (804, 'Bulianhe', 'CN', 804);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (805, 'Banghai', 'CN', 805);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (806, 'Karangampel', 'ID', 806);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (807, 'Baruchowo', 'PL', 807);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (808, 'Skanör', 'SE', 808);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (809, 'Cocorná', 'CO', 809);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (810, 'San Antonio', 'PE', 810);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (811, 'Marcovia', 'HN', 811);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (812, 'Datong', 'CN', 812);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (813, 'Taoyao', 'CN', 813);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (814, 'Vaasa', 'FI', 814);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (815, 'Nakhchivan', 'AZ', 815);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (816, 'Baní', 'DO', 816);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (817, 'Xinzhai', 'CN', 817);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (818, 'Wydminy', 'PL', 818);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (819, 'Gadang', 'ID', 819);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (820, 'Jianqiao', 'CN', 820);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (821, 'Cengang', 'CN', 821);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (822, 'Puerto Padre', 'CU', 822);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (823, 'Kisarawe', 'TZ', 823);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (824, 'Tamel', 'PT', 824);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (825, 'Liběšice', 'CZ', 825);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (826, 'Haixing', 'CN', 826);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (827, 'Niujiang', 'CN', 827);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (828, 'Mumias', 'KE', 828);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (829, 'Pančevo', 'RS', 829);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (830, 'Semey', 'KZ', 830);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (831, 'Wongka', 'ID', 831);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (832, 'Święciechowa', 'PL', 832);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (833, 'Béja', 'TN', 833);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (834, 'Kalmar', 'SE', 834);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (835, 'Strasbourg', 'FR', 835);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (836, 'Pionerskiy', 'RU', 836);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (837, 'Jurh', 'CN', 837);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (838, 'Pailiao', 'CN', 838);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (839, 'Sapouy', 'BF', 839);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (840, 'Yangdi', 'CN', 840);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (841, 'Tupesy', 'CZ', 841);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (842, 'Lingkou', 'CN', 842);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (843, 'Wobulenzi', 'UG', 843);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (844, 'Zuya', 'UA', 844);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (845, 'Nowa Sarzyna', 'PL', 845);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (846, 'Larreynaga', 'NI', 846);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (847, 'Pucangkrajan', 'ID', 847);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (848, 'Winong', 'ID', 848);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (849, 'Cikaduen', 'ID', 849);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (850, 'Jaboatão', 'BR', 850);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (851, 'Gvardeysk', 'RU', 851);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (852, 'Azovo', 'RU', 852);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (853, 'Övertorneå', 'SE', 853);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (854, 'Alvito', 'PT', 854);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (855, 'Littleton', 'US', 855);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (856, 'Colima', 'CR', 856);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (857, 'Khon San', 'TH', 857);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (858, 'Padova', 'IT', 858);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (859, 'Guachucal', 'CO', 859);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (860, 'Huanghu', 'CN', 860);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (861, 'Runka', 'NG', 861);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (862, 'Pingfeng', 'CN', 862);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (863, 'Fuliang', 'CN', 863);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (864, 'Espera Feliz', 'BR', 864);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (865, 'Xincun', 'CN', 865);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (866, 'Beiyang', 'CN', 866);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (867, 'Al Qardāḩah', 'SY', 867);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (868, 'Chaoyangdong', 'CN', 868);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (869, 'Gambaru', 'NG', 869);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (870, 'Velikooktyabr’skiy', 'RU', 870);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (871, 'Bira', 'RU', 871);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (872, 'Mhlume', 'SZ', 872);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (873, 'Jinqiao', 'CN', 873);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (874, 'Lanling', 'CN', 874);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (875, 'Praia da Tocha', 'PT', 875);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (876, 'Ube', 'JP', 876);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (877, 'Mahébourg', 'MU', 877);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (878, 'Aveiro', 'PT', 878);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (879, 'Acheng', 'CN', 879);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (880, 'Maradi', 'NE', 880);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (881, 'Union', 'PH', 881);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (882, 'Bessonovka', 'RU', 882);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (883, 'Las Vegas', 'HN', 883);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (884, 'Kamubheka', 'ID', 884);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (885, 'Putang', 'CN', 885);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (886, 'Mġarr', 'MT', 886);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (887, 'Niterói', 'BR', 887);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (888, 'Alue Glumpang', 'ID', 888);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (889, 'Zaïo', 'MA', 889);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (890, 'Sinuknipan', 'PH', 890);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (891, 'Bouaflé', 'CI', 891);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (892, 'Wedoro', 'ID', 892);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (893, 'Tairan Camp', 'PH', 893);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (894, 'Antes', 'PT', 894);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (895, 'Cergy-Pontoise', 'FR', 895);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (896, 'Wuxing', 'CN', 896);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (897, 'Pantang', 'CN', 897);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (898, 'Dolní Černilov', 'CZ', 898);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (899, 'Callao', 'PE', 899);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (900, 'Hāgere Hiywet', 'ET', 900);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (901, 'Trstenik', 'RS', 901);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (902, 'Stegna', 'PL', 902);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (903, 'La Labor', 'HN', 903);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (904, 'Pakalongan', 'ID', 904);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (905, 'Mailag', 'PH', 905);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (906, 'Lijie', 'CN', 906);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (907, 'Solânea', 'BR', 907);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (908, 'Xinxing', 'CN', 908);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (909, 'Onega', 'RU', 909);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (910, 'Mladá Boleslav', 'CZ', 910);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (911, 'Cruces', 'CU', 911);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (912, 'Ben Arous', 'TN', 912);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (913, 'Orvalho', 'PT', 913);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (914, 'Ternovka', 'RU', 914);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (915, 'Longbei', 'CN', 915);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (916, 'Orillia', 'CA', 916);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (917, 'Oenam', 'ID', 917);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (918, 'Oekero', 'ID', 918);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (919, 'Nankou', 'CN', 919);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (920, 'Kuching', 'MY', 920);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (921, 'Brest', 'FR', 921);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (922, 'Falun', 'SE', 922);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (923, 'Susaki', 'JP', 923);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (924, 'Ajuy', 'PH', 924);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (925, 'Gayamdesa', 'ID', 925);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (926, 'Atamanovka', 'RU', 926);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (927, 'Rutul', 'RU', 927);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (928, 'Sirari', 'TZ', 928);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (929, 'Kasese', 'UG', 929);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (930, 'Hinthada', 'MM', 930);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (931, 'Itapaci', 'BR', 931);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (932, 'Ndom', 'CM', 932);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (933, 'Piterka', 'RU', 933);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (934, 'Armentières', 'FR', 934);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (935, 'Wadusari', 'ID', 935);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (936, 'Krajan Puru', 'ID', 936);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (937, 'Petaling Jaya', 'MY', 937);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (938, 'Nyanza', 'RW', 938);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (939, 'Valle de Ángeles', 'HN', 939);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (940, 'L-Iklin', 'MT', 940);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (941, 'Desamparados', 'CR', 941);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (942, 'Jingjiang', 'CN', 942);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (943, 'Noling', 'PH', 943);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (944, 'Nakło nad Notecią', 'PL', 944);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (945, 'Cam Ranh', 'VN', 945);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (946, 'Kuzhorskaya', 'RU', 946);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (947, 'Salawu', 'ID', 947);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (948, 'Bongued', 'PH', 948);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (949, 'Houping', 'CN', 949);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (950, 'Oepuah', 'ID', 950);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (951, 'Beaconsfield', 'CA', 951);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (952, 'Polyarnyye Zori', 'RU', 952);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (953, 'Krajan Siki', 'ID', 953);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (954, 'Qiaozhuang', 'CN', 954);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (955, 'Prapen', 'ID', 955);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (956, 'Pytalovo', 'RU', 956);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (957, 'Minuyan', 'PH', 957);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (958, 'Mujiangping', 'CN', 958);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (959, 'Tlogowetan', 'ID', 959);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (960, 'San José Poaquil', 'GT', 960);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (961, 'Castlepollard', 'IE', 961);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (962, 'Agriá', 'GR', 962);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (963, 'Madrid', 'ES', 963);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (964, 'Banjar Budakeling', 'ID', 964);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (965, 'Koilás', 'GR', 965);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (966, 'Blois', 'FR', 966);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (967, 'Siguiri', 'GN', 967);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (968, 'Thành Phố Nam Định', 'VN', 968);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (969, 'Duisburg', 'DE', 969);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (970, 'Zouma', 'CN', 970);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (971, 'Halmstad', 'SE', 971);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (972, 'Kapsabet', 'KE', 972);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (973, 'Khlevnoye', 'RU', 973);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (974, 'Omaha', 'US', 974);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (975, 'Beiguoyuan', 'CN', 975);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (976, 'Palekastro', 'GR', 976);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (977, 'Privodino', 'RU', 977);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (978, 'Sokhumi', 'GE', 978);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (979, 'Isiolo', 'KE', 979);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (980, 'El Caño', 'PA', 980);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (981, 'Port-Gentil', 'GA', 981);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (982, 'Baisha', 'CN', 982);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (983, 'Kambatatamakawu', 'ID', 983);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (984, 'Lasusua', 'ID', 984);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (985, 'Jutrosin', 'PL', 985);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (986, 'Longsheng', 'CN', 986);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (987, 'Stratford', 'CA', 987);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (988, 'Suugaant', 'MN', 988);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (989, 'Mengenkrajan', 'ID', 989);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (990, 'Rzozów', 'PL', 990);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (991, 'Ambato', 'EC', 991);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (992, 'Bojano', 'PL', 992);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (993, 'Nässjö', 'SE', 993);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (994, 'Gongji', 'CN', 994);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (995, 'Viraco', 'PE', 995);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (996, 'Trondheim', 'NO', 996);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (997, 'Flen', 'SE', 997);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (998, 'Maciejowice', 'PL', 998);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (999, 'Vale de Rolas', 'PT', 999);
insert into ESTADO (ID, NOMBRE, ABREVIATURA, PAIS_ID) values (1000, 'Xiangba', 'CN', 1000);
