INSERT INTO PAIS (ID, NOMBRE, ABREVIATURA) VALUES (1, 'México', 'MX');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (2, 'Encantado', 'BR');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (3, 'Rancaseneng', 'ID');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (4, 'Kaligutan', 'PH');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (5, 'Lukou', 'CN');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (6, 'Zhenlai', 'CN');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (7, 'Tanahmerah', 'ID');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (8, 'Caqu', 'CN');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (9, 'Pontevedra', 'ES');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (10, 'Kochani', 'MK');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (11, 'Xiongguan', 'CN');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (12, 'Danderyd', 'SE');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (13, 'Annecy', 'FR');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (14, 'Cantilan', 'PH');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (15, 'Gwangtan', 'KR');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (16, 'Ibaté', 'BR');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (17, 'Numazu', 'JP');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (18, 'Kiuruvesi', 'FI');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (19, 'Deshan', 'CN');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (20, 'Olmos', 'PE');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (21, 'Nay Pyi Taw', 'MM');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (22, 'Świlcza', 'PL');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (23, 'Colquemarca', 'PE');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (24, 'Longfengshan', 'CN');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (25, 'Daja Lorong', 'ID');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (26, 'Mikró Monastíri', 'GR');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (27, 'Aquia', 'PE');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (28, 'Pindangan Centro', 'PH');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (29, 'Culianin', 'PH');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (30, 'Fengtai Chengguanzhen', 'CN');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (31, 'Idah', 'NG');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (32, 'Moxi', 'CN');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (33, 'Panggungsari', 'ID');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (34, 'Guojiazhuang', 'CN');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (35, 'Gunungmenang', 'ID');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (36, 'Dordrecht', 'NL');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (37, 'Águas Formosas', 'BR');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (38, 'Midleton', 'IE');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (39, 'Pyhäjoki', 'FI');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (40, 'Kebonagung', 'ID');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (41, 'Một Ngàn', 'VN');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (42, 'Somita', 'GM');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (43, 'Khān Arnabah', 'SY');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (44, 'Douala', 'CM');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (45, 'Tyczyn', 'PL');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (46, 'Sukamulya', 'ID');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (47, 'Lagny-sur-Marne', 'FR');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (48, 'Shuangkou', 'CN');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (49, 'Houping', 'CN');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (50, 'Nasilava', 'BY');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (51, 'Tacurong', 'PH');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (52, 'Pekuwon', 'ID');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (53, 'Gravataí', 'BR');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (54, 'Ban Lam Luk Ka', 'TH');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (55, 'Xiayang', 'CN');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (56, 'Zhangjiayuan', 'CN');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (57, 'Tacna', 'PE');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (58, 'Uddevalla', 'SE');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (59, 'Mengmeng', 'CN');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (60, 'Toulon', 'FR');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (61, 'Brovary', 'UA');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (62, 'Ciawitali', 'ID');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (63, 'Papineauville', 'CA');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (64, 'Corpus Christi', 'US');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (65, 'Skwierzyna', 'PL');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (66, 'Mikhnëvo', 'RU');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (67, 'Baranovichi', 'BY');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (68, 'Yuejin', 'CN');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (69, 'Changping', 'CN');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (70, 'Beirut', 'LB');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (71, 'Neuville', 'CA');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (72, 'São Pedro do Estoril', 'PT');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (73, 'Ipil', 'PH');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (74, 'Mishima', 'JP');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (75, 'Kōfu-shi', 'JP');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (76, 'Kaom', 'ID');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (77, 'Gostyń', 'PL');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (78, 'Vysokogornyy', 'RU');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (79, 'Jucás', 'BR');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (80, 'Brisbane', 'AU');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (81, 'Brejoeira', 'PT');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (82, 'Kota Kinabalu', 'MY');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (83, 'La Poma', 'AR');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (84, 'Krajan Tengah', 'ID');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (85, 'Hamburg', 'DE');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (86, 'Épinal', 'FR');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (87, 'Kertabumi', 'ID');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (88, 'Mohammedia', 'MA');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (89, 'Suqu', 'CN');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (90, 'Seattle', 'US');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (91, 'Krajan Karanganyar', 'ID');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (92, 'Palermo', 'IT');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (93, 'Rungis', 'FR');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (94, 'Zahlé', 'LB');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (95, 'Phùng', 'VN');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (96, 'Malakal', 'SS');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (97, 'Karangsari', 'ID');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (98, 'Zavety Il’icha', 'RU');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (99, 'Trzebunia', 'PL');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (100, 'Buchach', 'UA');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (101, 'Brisbane', 'AU');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (102, 'Wiphawadi', 'TH');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (103, 'Shigongqiao', 'CN');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (104, 'Trudobelikovskiy', 'RU');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (105, 'Xuedian', 'CN');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (106, 'Pochep', 'RU');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (107, 'Baghlān', 'AF');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (108, 'Koz’modem’yansk', 'RU');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (109, 'Horní Jiřetín', 'CZ');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (110, 'Cabitan', 'PH');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (111, 'Novoaleksandrovsk', 'RU');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (112, 'Soure', 'PT');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (113, 'Nueve de Julio', 'AR');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (114, 'Panyingkiran', 'ID');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (115, 'Sapang Buho', 'PH');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (116, 'Tolitoli', 'ID');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (117, 'Mirotice', 'CZ');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (118, 'Makanya', 'TZ');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (119, 'Dashtavan', 'AM');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (120, 'Zhongcheng', 'CN');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (121, 'Zangkaxa', 'CN');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (122, 'Korsakovo', 'RU');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (123, 'Kętrzyn', 'PL');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (124, 'Wanglinkou', 'CN');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (125, 'Santiago', 'PH');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (126, 'Hīsh', 'SY');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (127, 'Rincón', 'DO');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (128, 'Kerek', 'ID');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (129, 'Stari Banovci', 'RS');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (130, 'Qusar', 'AZ');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (131, 'Elói Mendes', 'BR');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (132, 'Cầu Gồ', 'VN');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (133, 'Longquan', 'CN');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (134, 'Kaliterus', 'ID');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (135, 'Macatuba', 'BR');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (136, 'São Bento', 'PT');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (137, 'Phúc Yên', 'VN');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (138, 'Dinan', 'FR');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (139, 'Zhoutie', 'CN');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (140, 'Sanqiao', 'CN');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (141, 'Dokshytsy', 'BY');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (142, 'Baoli', 'CN');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (143, 'Santa Rita', 'PY');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (144, 'Pitangueiras', 'BR');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (145, 'Mukayrās', 'YE');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (146, 'Järfälla', 'SE');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (147, 'Mingelchaur', 'AZ');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (148, 'Ligang', 'CN');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (149, 'Tetandara', 'ID');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (150, 'Pinhal General', 'PT');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (151, 'Shijiazhai', 'CN');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (152, 'Listvyanka', 'RU');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (153, 'Yaurisque', 'PE');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (154, 'Kista', 'SE');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (155, 'Póvoa', 'PT');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (156, 'Lao Suea Kok', 'TH');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (157, 'Buliran Segundo', 'PH');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (158, 'Eleftheroúpolis', 'GR');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (159, 'Aksarka', 'RU');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (160, 'Mailsi', 'PK');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (161, 'Retenggoma', 'ID');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (162, 'Vardenik', 'AM');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (163, 'Dakoutun', 'CN');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (164, 'Chillán', 'CL');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (165, 'Birmingham', 'US');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (166, 'Murree', 'PK');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (167, 'Shirone', 'JP');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (168, 'Shuigou', 'CN');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (169, 'Solnice', 'CZ');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (170, 'Mońki', 'PL');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (171, 'Sonina', 'PL');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (172, 'Taoling', 'CN');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (173, 'Dobratice', 'CZ');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (174, 'Isaka', 'TZ');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (175, 'Huzhen', 'CN');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (176, 'Jiangyin', 'CN');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (177, 'Quanxi', 'CN');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (178, 'Krajan', 'ID');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (179, 'Ribeiro', 'PT');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (180, 'Cagmanaba', 'PH');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (181, 'Pueblo Nuevo', 'PA');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (182, 'Kham Sakae Saeng', 'TH');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (183, 'Al Karāmah', 'SY');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (184, 'Cueto', 'CU');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (185, 'Kebon', 'ID');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (186, 'Bulacnin', 'PH');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (187, 'Karangasem', 'ID');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (188, 'Värnamo', 'SE');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (189, 'Bringinanom', 'ID');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (190, 'Hexi', 'CN');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (191, 'Sobotka', 'CZ');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (192, 'Rancapanjang', 'ID');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (193, 'Zachepylivka', 'UA');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (194, 'Hule', 'CN');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (195, 'Lyon', 'FR');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (196, 'Mekarsari', 'ID');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (197, 'Bato', 'PH');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (198, 'Buenos Aires', 'MX');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (199, 'Moñitos', 'CO');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (200, 'Baguinge', 'PH');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (201, 'Hyesan-dong', 'KP');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (202, 'Ninghai', 'CN');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (203, 'Candi', 'ID');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (204, 'Lào Cai', 'VN');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (205, 'Zhushan', 'CN');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (206, 'Nové Město pod Smrkem', 'CZ');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (207, 'Polel Diaoubé', 'SN');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (208, 'Sukkozero', 'RU');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (209, 'Qiting', 'CN');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (210, 'Liufu', 'CN');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (211, 'Maroantsetra', 'MG');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (212, 'Semampirbarat', 'ID');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (213, 'Yugawara', 'JP');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (214, 'Fanrong', 'CN');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (215, 'Zhanlong', 'CN');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (216, 'Hato Mayor del Rey', 'DO');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (217, 'Menggala', 'ID');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (218, 'Repušnica', 'HR');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (219, 'Halmstad', 'SE');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (220, 'Citarik', 'ID');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (221, 'Mindupok', 'PH');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (222, 'Santa Rosa', 'MX');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (223, 'Thị Trấn Thọ Xuân', 'VN');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (224, 'Yishui', 'CN');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (225, 'Dabbūrīya', 'IL');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (226, 'Choa Saidān Shāh', 'PK');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (227, 'Magetlegar', 'ID');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (228, 'Kotlyarevskaya', 'RU');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (229, 'Simpanganduwet', 'ID');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (230, 'Dongfeng', 'CN');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (231, 'Dolany', 'CZ');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (232, 'Baranusa', 'ID');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (233, 'Dajin', 'CN');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (234, 'Stamáta', 'GR');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (235, 'Marne-la-Vallée', 'FR');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (236, 'Tarīm', 'YE');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (237, 'Maglajani', 'BA');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (238, 'Podgorica', 'ME');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (239, 'Funan Chengguanzhen', 'CN');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (240, 'El Zulia', 'CO');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (241, 'Verkhniy Avzyan', 'RU');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (242, 'Artsvanist', 'AM');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (243, 'Tapado', 'PT');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (244, 'Gia Nghĩa', 'VN');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (245, 'Kutacane', 'ID');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (246, 'Bauru', 'BR');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (247, 'Khotiv', 'UA');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (248, 'Bondoufle', 'FR');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (249, 'Taokeng', 'CN');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (250, 'San Miguel Dueñas', 'GT');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (251, 'Wuyanquan', 'CN');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (252, 'Kembangan', 'ID');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (253, 'Thākurgaon', 'BD');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (254, 'Wiri', 'NZ');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (255, 'Youwarou', 'ML');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (256, 'Redondos', 'PT');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (257, 'Igboho', 'NG');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (258, 'Greensboro', 'US');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (259, 'Pukë', 'AL');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (260, 'Hengjiang', 'CN');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (261, 'Taiping', 'MY');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (262, 'Wuqiao', 'CN');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (263, 'Citeureup', 'ID');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (264, 'Kassiri', 'SL');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (265, 'Līvāni', 'LV');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (266, 'Masohi', 'ID');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (267, 'Shangjin', 'CN');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (268, 'Kedungbulu', 'ID');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (269, 'Nishishinminato', 'JP');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (270, 'Chemerivtsi', 'UA');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (271, 'Broby', 'FI');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (272, 'Bundibugyo', 'UG');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (273, 'Cheonan', 'KR');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (274, 'Ninghai', 'CN');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (275, 'Stěžery', 'CZ');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (276, 'Kučevo', 'RS');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (277, 'Padangguci', 'ID');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (278, 'Boulogne-sur-Mer', 'FR');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (279, 'Tanggung', 'ID');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (280, 'Söderhamn', 'SE');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (281, 'Sävedalen', 'SE');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (282, 'Samannūd', 'EG');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (283, 'Tsagaandörvölj', 'MN');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (284, 'Koatas Lao', 'ID');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (285, 'Apoya', 'PH');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (286, 'Kil’mez’', 'RU');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (287, 'Malaga', 'ES');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (288, 'Murzuq', 'LY');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (289, 'Bozoum', 'CF');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (290, 'Metz', 'FR');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (291, 'Hualmay', 'PE');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (292, 'Longfengba', 'CN');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (293, 'Haiyanmiao', 'CN');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (294, 'Ciemas', 'ID');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (295, 'Dong Charoen', 'TH');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (296, 'Zaojiacheng', 'CN');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (297, 'Adelaide Mail Centre', 'AU');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (298, 'Kozy', 'PL');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (299, 'Caitang', 'CN');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (300, 'Manzanillo', 'CU');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (301, 'Ngenden', 'ID');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (302, 'Pengandonan', 'ID');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (303, 'Glasgow', 'GB');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (304, 'Caucasia', 'CO');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (305, 'Minyat an Naşr', 'EG');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (306, 'Patsi', 'KM');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (307, 'Mikhaylov', 'RU');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (308, 'Wolmaransstad', 'ZA');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (309, 'Borås', 'SE');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (310, 'Lobamba', 'SZ');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (311, 'Tramandaí', 'BR');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (312, 'Mojoroto', 'ID');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (313, 'Tigaon', 'PH');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (314, 'Merefa', 'UA');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (315, 'Oenpeotnai', 'ID');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (316, 'Staryy Sambor', 'UA');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (317, 'Tālīn', 'SY');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (318, 'Kavieng', 'PG');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (319, 'Santa Rita', 'VE');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (320, 'Dourbali', 'TD');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (321, 'Caicun', 'CN');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (322, 'Batelov', 'CZ');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (323, 'Ciechanów', 'PL');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (324, 'Lloque', 'PE');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (325, 'Rio de Janeiro', 'BR');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (326, 'Smålandsstenar', 'SE');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (327, 'Imbituva', 'BR');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (328, 'São Mateus do Maranhão', 'BR');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (329, 'Portela', 'PT');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (330, 'Huji', 'CN');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (331, 'Paris 01', 'FR');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (332, 'Cempa', 'ID');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (333, 'Yangxiang', 'CN');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (334, 'Xiatuanpu', 'CN');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (335, 'Alivéri', 'GR');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (336, 'Sines', 'PT');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (337, 'Niquelândia', 'BR');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (338, 'Berkovitsa', 'BG');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (339, 'Zadawa', 'NG');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (340, 'Songgai', 'CN');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (341, 'Keumala', 'ID');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (342, 'Gonghe', 'CN');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (343, 'Hongshunli', 'CN');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (344, 'Dagang', 'CN');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (345, 'Isahaya', 'JP');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (346, 'Balaoang', 'PH');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (347, 'Waso', 'ID');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (348, 'Hongxingqiao', 'CN');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (349, 'Stockholm', 'SE');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (350, 'Meliau', 'ID');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (351, 'Fontenay-sous-Bois', 'FR');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (352, 'Feni', 'BD');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (353, 'Lingxi', 'CN');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (354, 'Rublëvo', 'RU');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (355, 'Memphis', 'US');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (356, 'Sayyān', 'YE');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (357, 'Mariquita', 'CO');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (358, 'Qushi’an', 'CN');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (359, 'Zolotonosha', 'UA');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (360, 'Ríohacha', 'CO');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (361, 'Agarsin', 'CN');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (362, 'Lyon', 'FR');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (363, 'Brooklyn', 'US');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (364, 'Cincinnati', 'US');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (365, 'Shah Alam', 'MY');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (366, 'Kotawaikabubak', 'ID');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (367, 'Zhangdian', 'CN');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (368, 'Kenzhe', 'RU');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (369, 'Ichihara', 'JP');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (370, 'Tuofeng', 'CN');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (371, 'Chợ Gạo', 'VN');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (372, 'Černožice', 'CZ');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (373, 'Erie', 'US');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (374, 'Luklukan', 'PH');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (375, 'Saint Louis', 'US');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (376, 'Haicheng', 'CN');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (377, 'Gorno Orizari', 'MK');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (378, 'Itinga', 'BR');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (379, 'Kaczory', 'PL');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (380, 'Písečná', 'CZ');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (381, 'Zhangcun', 'CN');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (382, 'Anabar', 'NR');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (383, 'Azurduy', 'BO');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (384, 'Ballinroad', 'IE');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (385, 'Huayuan', 'CN');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (386, 'Johanneshov', 'SE');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (387, 'Āsasa', 'ET');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (388, 'Coayllo', 'PE');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (389, 'Xinghe Chengguanzhen', 'CN');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (390, 'Muara', 'ID');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (391, 'Bulakbanjar', 'ID');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (392, 'Daugavpils', 'LV');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (393, 'Göteborg', 'SE');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (394, 'Changshan', 'CN');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (395, 'Cimişlia', 'MD');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (396, 'Cesvaine', 'LV');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (397, 'Xiangzhu', 'CN');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (398, 'Filiátes', 'GR');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (399, 'Tarui', 'JP');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (400, 'Pasirnangka', 'ID');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (401, 'Huangzhan', 'CN');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (402, 'Brumadinho', 'BR');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (403, 'Shankeng', 'CN');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (404, 'Neochóri', 'GR');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (405, 'Pardesiyya', 'IL');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (406, 'Krasnoarmiys’k', 'UA');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (407, 'Darfield', 'NZ');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (408, 'Shetan', 'CN');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (409, 'Boguchwała', 'PL');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (410, 'Omoku', 'NG');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (411, 'Zbarazh', 'UA');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (412, 'Mesyagutovo', 'RU');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (413, 'Skalánion', 'GR');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (414, 'Houston', 'US');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (415, 'Kopidlno', 'CZ');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (416, 'Cisasak', 'ID');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (417, 'Anchorage', 'US');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (418, 'Khadzhalmakhi', 'RU');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (419, 'Sadabumi', 'ID');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (420, 'Stockholm', 'SE');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (421, 'Tanarara', 'ID');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (422, 'Sungi Liput', 'ID');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (423, 'Bourges', 'FR');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (424, 'Sarimukti Kaler', 'ID');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (425, 'Subrag', 'CN');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (426, 'Qiting', 'CN');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (427, 'Zhanjia', 'CN');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (428, 'Águas Vermelhas', 'BR');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (429, 'Urshel’skiy', 'RU');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (430, 'Abengourou', 'CI');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (431, 'Primorsko-Akhtarsk', 'RU');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (432, 'Puerto de Nutrias', 'VE');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (433, 'Abū Tīj', 'EG');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (434, 'Alfta', 'SE');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (435, 'Linköping', 'SE');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (436, 'Kombapari', 'ID');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (437, 'Ekenäs', 'FI');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (438, 'Bishkek', 'KG');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (439, 'Drammen', 'NO');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (440, 'Sumurasin', 'ID');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (441, 'Encruzilhada do Sul', 'BR');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (442, 'Sindangsari', 'ID');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (443, 'Jiuli', 'CN');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (444, 'Desē', 'ET');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (445, 'Indianapolis', 'US');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (446, 'Zhouzhuang', 'CN');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (447, 'Canavieiras', 'BR');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (448, 'Stąporków', 'PL');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (449, 'Stará Ves nad Ondřejnicí', 'CZ');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (450, 'Batubantar', 'ID');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (451, 'Yonggu', 'CN');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (452, 'Arboga', 'SE');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (453, 'Sagrada Familia', 'PH');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (454, 'Huaiya', 'CN');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (455, 'Gaoqiao', 'CN');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (456, 'Tinaco', 'VE');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (457, 'Breda', 'NL');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (458, 'Jinja', 'UG');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (459, 'Mander', 'ID');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (460, 'Châlons-en-Champagne', 'FR');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (461, 'Pasirmanggu', 'ID');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (462, 'Viesīte', 'LV');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (463, 'Wolomarang', 'ID');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (464, 'San Diego', 'US');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (465, 'Vakhrushi', 'RU');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (466, 'Pudoc', 'PH');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (467, 'Obama', 'JP');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (468, 'Umeå', 'SE');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (469, 'Krajan', 'ID');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (470, 'Osiek', 'PL');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (471, 'Taipingxu', 'CN');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (472, 'Burujul', 'ID');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (473, 'Rancamaya', 'ID');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (474, 'Bairro Assunção Piedade', 'PT');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (475, 'Karakol', 'KG');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (476, 'Socabaya', 'PE');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (477, 'Biên Hòa', 'VN');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (478, 'Huangtu', 'CN');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (479, 'Chongwen', 'CN');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (480, 'Genting', 'ID');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (481, 'Praia da Vagueira', 'PT');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (482, 'Hujia', 'CN');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (483, 'Pierzchnica', 'PL');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (484, 'Jiaqu', 'CN');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (485, 'Selorejo', 'ID');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (486, 'Jiaoshanhe', 'CN');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (487, 'České Meziříčí', 'CZ');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (488, 'Xinlong', 'CN');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (489, 'Rennes', 'FR');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (490, 'Yarumela', 'HN');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (491, 'Kham Sakae Saeng', 'TH');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (492, 'Quintas', 'PT');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (493, 'Rancabuaya', 'ID');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (494, 'Maurisu', 'ID');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (495, 'Huashixia', 'CN');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (496, 'Xianglan', 'CN');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (497, 'Muarasiau', 'ID');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (498, 'Lalmanirhat', 'BD');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (499, 'Janikowo', 'PL');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (500, 'Sibagat', 'PH');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (501, 'Tarui', 'JP');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (502, 'Caicedonia', 'CO');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (503, 'Višnjevac', 'HR');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (504, 'Saboyá', 'CO');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (505, 'Arísvi', 'GR');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (506, 'Girijaya', 'ID');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (507, 'Ribeirão Preto', 'BR');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (508, 'Nashtā Rūd', 'IR');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (509, 'Liloan', 'PH');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (510, 'Kotabumi', 'ID');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (511, 'Rentung', 'ID');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (512, 'Tanjungampalu', 'ID');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (513, 'Alindao', 'CF');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (514, 'Xiushi', 'CN');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (515, 'Boshan', 'CN');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (516, 'Stockholm', 'SE');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (517, 'Piritiba', 'BR');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (518, 'Osiek nad Notecią', 'PL');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (519, 'Mingzhong', 'CN');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (520, 'Parang', 'PH');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (521, 'Olival Basto', 'PT');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (522, 'Övertorneå', 'SE');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (523, 'Zhuge', 'CN');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (524, 'Almolonga', 'GT');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (525, 'Wonda', 'ID');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (526, 'Urazovka', 'RU');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (527, 'Licun', 'CN');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (528, 'Cocachacra', 'PE');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (529, 'Kourou', 'GF');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (530, 'Sumenep', 'ID');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (531, 'Pujilí', 'EC');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (532, 'Kaset Sombun', 'TH');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (533, 'Mokil', 'FM');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (534, 'Falkenberg', 'SE');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (535, 'Moorreesburg', 'ZA');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (536, 'Nuga', 'MN');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (537, 'Montilla', 'PH');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (538, 'Golug', 'CN');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (539, 'Aston', 'GB');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (540, 'Cilangla', 'ID');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (541, 'Nilópolis', 'BR');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (542, 'Kishiwada', 'JP');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (543, 'Sagang', 'PH');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (544, 'Villa Dolores', 'AR');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (545, 'Néo Psychikó', 'GR');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (546, 'L''viv', 'UA');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (547, 'Bethlehem', 'ZA');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (548, 'San Antonio', 'HN');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (549, 'Myingyan', 'MM');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (550, 'Yurla', 'RU');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (551, 'Armenokhórion', 'GR');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (552, 'Penelas', 'PT');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (553, 'Liufu', 'CN');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (554, 'Ma Đa Gui', 'VN');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (555, 'Železnice', 'CZ');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (556, 'Kakogawachō-honmachi', 'JP');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (557, 'San Jorge', 'AR');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (558, 'Jinsha', 'CN');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (559, 'Boavista', 'PT');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (560, 'Kohlu', 'PK');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (561, 'Outeiro de Polima', 'PT');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (562, 'Soko', 'ID');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (563, 'Dalai', 'CN');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (564, 'Xingguo', 'CN');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (565, 'Johanneshov', 'SE');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (566, 'Chiconi', 'YT');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (567, 'Labuan', 'MY');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (568, 'Tualeu', 'ID');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (569, 'Lalupon', 'NG');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (570, 'Santa Magdalena', 'PH');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (571, 'Cerro Corá', 'AR');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (572, 'Queniquea', 'VE');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (573, 'Huangjinbu', 'CN');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (574, 'Bedford', 'CA');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (575, 'Goubétto', 'DJ');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (576, 'Tinalmud', 'PH');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (577, 'Yuquan', 'CN');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (578, 'Suan Luang', 'TH');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (579, 'Vanino', 'RU');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (580, 'Ángeles', 'CR');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (581, 'Tsivil’sk', 'RU');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (582, 'Shuakhevi', 'GE');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (583, 'Tintina', 'AR');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (584, 'Senduro', 'ID');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (585, 'Calape', 'PH');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (586, 'Pitalito', 'CO');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (587, 'Kutampi', 'ID');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (588, 'Dongbatu', 'CN');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (589, 'Taiyigong', 'CN');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (590, 'Thị Trấn Than Uyên', 'VN');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (591, 'Bridel', 'LU');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (592, 'Bang Sao Thong', 'TH');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (593, 'Cintra', 'AR');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (594, 'Portland', 'US');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (595, 'Dniprodzerzhyns’k', 'UA');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (596, 'Sysert’', 'RU');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (597, 'Benito Juarez', 'MX');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (598, 'Yuandun', 'CN');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (599, 'Allada', 'BJ');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (600, 'New York City', 'US');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (601, 'Sinjhoro', 'PK');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (602, 'Vostryakovo', 'RU');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (603, 'Silva Jardim', 'BR');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (604, 'Semënovskoye', 'RU');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (605, 'Asbest', 'RU');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (606, 'Xinghe Chengguanzhen', 'CN');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (607, 'Łękawica', 'PL');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (608, 'Al Ghuwayrīyah', 'QA');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (609, 'Estância', 'BR');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (610, 'Honolulu', 'US');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (611, 'Raczki', 'PL');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (612, 'Krajan', 'ID');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (613, 'Shpola', 'UA');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (614, 'Ngilengan', 'ID');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (615, 'Syntul', 'RU');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (616, 'Inuvik', 'CA');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (617, 'Lancaster', 'US');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (618, 'Anjozorobe', 'MG');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (619, 'Digah', 'AZ');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (620, 'Paris 14', 'FR');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (621, 'Yangju', 'KR');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (622, 'Colonia Mauricio José Troche', 'PY');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (623, 'Zhoujia', 'CN');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (624, 'Xianhe', 'CN');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (625, 'Hacıqabul', 'AZ');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (626, 'Parikkala', 'FI');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (627, 'Sukowiryo', 'ID');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (628, 'Chalan Pago-Ordot Village', 'GU');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (629, 'Cantilan', 'PH');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (630, 'Lahān', 'NP');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (631, 'Rancamaya', 'ID');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (632, 'Maldonado', 'UY');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (633, 'Tufang', 'CN');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (634, 'Leitões', 'PT');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (635, 'Massaguet', 'TD');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (636, 'Irbit', 'RU');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (637, 'Kahama', 'TZ');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (638, 'Huaxian', 'CN');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (639, 'Kyosai', 'KR');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (640, 'Kladanj', 'BA');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (641, 'Madalena', 'PT');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (642, 'Batukuta', 'ID');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (643, 'Limen', 'CN');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (644, 'Da’ao', 'CN');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (645, 'Yipeng', 'CN');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (646, 'Hrazdan', 'AM');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (647, 'Huangtan', 'CN');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (648, 'Baru Timur', 'ID');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (649, 'Obo', 'CF');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (650, 'K’anak’erravan', 'AM');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (651, 'Cerca la Source', 'HT');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (652, 'Calubcub Dos', 'PH');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (653, 'Pedro Betancourt', 'CU');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (654, 'Honghualiangzi', 'CN');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (655, 'Bartolomé Masó', 'CU');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (656, 'Maanĭt', 'MN');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (657, 'Pyin Oo Lwin', 'MM');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (658, 'São Marcos', 'BR');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (659, 'Libmanan', 'PH');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (660, 'Göteborg', 'SE');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (661, 'Francisco I Madero', 'MX');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (662, 'Atlanta', 'US');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (663, 'Jatimulyo', 'ID');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (664, 'São Domingos do Maranhão', 'BR');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (665, 'Pansoy', 'PH');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (666, 'Forssa', 'FI');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (667, 'Osieck', 'PL');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (668, 'Martingança-Gare', 'PT');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (669, 'Armação de Búzios', 'BR');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (670, 'Ta’erqi', 'CN');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (671, 'Pasireurih', 'ID');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (672, 'Papër', 'AL');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (673, 'Claver', 'PH');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (674, 'Solna', 'SE');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (675, 'Kortesjärvi', 'FI');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (676, 'Monte Alto', 'BR');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (677, 'Ludbreg', 'HR');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (678, 'Ban Muang', 'TH');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (679, 'Matiguás', 'NI');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (680, 'Józefów', 'PL');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (681, 'Sobreiro', 'PT');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (682, 'Hadāli', 'PK');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (683, 'Yuekou', 'CN');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (684, 'Itajaí', 'BR');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (685, 'Tinampo', 'PH');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (686, 'Rasskazovo', 'RU');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (687, 'København', 'DK');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (688, 'Jakubowice Murowane', 'PL');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (689, 'Charenton-le-Pont', 'FR');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (690, 'Shishan', 'CN');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (691, 'Cajacay', 'PE');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (692, 'Náklo', 'CZ');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (693, 'Salt Lake City', 'US');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (694, 'Huquan', 'CN');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (695, 'Cap Malheureux', 'MU');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (696, 'Jiangnan', 'CN');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (697, 'Qingxi', 'CN');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (698, 'Sukasada', 'ID');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (699, 'Pickering', 'CA');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (700, 'Karolinka', 'CZ');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (701, 'Pamiątkowo', 'PL');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (702, 'Jāsk', 'IR');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (703, 'Ash Shafā', 'SA');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (704, 'Qingduizi', 'CN');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (705, 'Huyunxiang', 'CN');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (706, 'Novhorod-Sivers’kyy', 'UA');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (707, 'København', 'DK');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (708, 'Santa Rita', 'VE');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (709, 'Briceni', 'MD');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (710, 'Kaduela', 'ID');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (711, 'Calingcing', 'ID');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (712, 'Lota', 'CL');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (713, 'Sacotes', 'PT');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (714, 'Sukabumi', 'ID');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (715, 'Yangzhong', 'CN');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (716, 'Santo Domingo', 'CU');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (717, 'Minle', 'CN');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (718, 'Gonghe', 'CN');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (719, 'Yuanling', 'CN');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (720, 'Musashino', 'JP');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (721, 'Rochester', 'US');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (722, 'Belozërskoye', 'RU');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (723, 'Lešná', 'CZ');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (724, 'Huishi', 'CN');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (725, 'Kota Kinabalu', 'MY');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (726, 'Farīdpur', 'BD');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (727, 'Babao', 'CN');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (728, 'Vermelha', 'PT');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (729, 'Jūrmala', 'LV');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (730, 'San Luis Jilotepeque', 'GT');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (731, 'Novocherkassk', 'RU');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (732, 'Belo', 'CM');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (733, 'Roodepoort', 'ZA');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (734, 'Taipinghu', 'CN');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (735, 'Bor', 'RU');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (736, 'Horred', 'SE');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (737, 'Bor', 'RS');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (738, 'Laweueng', 'ID');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (739, 'Lamongan', 'ID');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (740, 'Shangsanji', 'CN');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (741, 'Purwosari', 'ID');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (742, 'Yinglong', 'CN');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (743, 'Tais', 'ID');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (744, 'La Paz', 'PH');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (745, 'Chixi', 'CN');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (746, 'Tyszowce', 'PL');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (747, 'Imtarfa', 'MT');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (748, 'Nova Kakhovka', 'UA');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (749, 'Dongkeng', 'CN');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (750, 'Ipoh', 'MY');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (751, 'Ampelákia', 'GR');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (752, 'Chiguata', 'PE');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (753, 'Amagarapati', 'ID');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (754, 'Houxi', 'CN');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (755, 'Serere', 'UG');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (756, 'Menglie', 'CN');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (757, 'Muarasiau', 'ID');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (758, 'Maojiagang', 'CN');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (759, 'Jaguimitan', 'PH');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (760, 'Aguachica', 'CO');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (761, 'Haodian', 'CN');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (762, 'Czemierniki', 'PL');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (763, 'Changhe', 'CN');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (764, 'Mahalapye', 'BW');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (765, 'Ash Shāmīyah', 'KW');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (766, 'Yasenskaya', 'RU');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (767, 'Venezia', 'IT');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (768, 'Bromma', 'SE');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (769, 'Louny', 'CZ');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (770, 'Tsubame', 'JP');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (771, 'Pittsburgh', 'US');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (772, 'Sanhui', 'CN');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (773, 'Belgorod', 'RU');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (774, 'Jiedu', 'CN');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (775, 'Sebadelhe', 'PT');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (776, 'Mambi', 'ID');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (777, 'Daniwato', 'ID');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (778, 'Tomioka', 'JP');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (779, 'Krajenka', 'PL');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (780, 'Betim', 'BR');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (781, 'Norrtälje', 'SE');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (782, 'Changyi', 'CN');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (783, 'Cisiec', 'PL');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (784, 'Shilovo', 'RU');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (785, 'Luzhou', 'CN');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (786, 'Zangzhai', 'CN');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (787, 'Cabuyaro', 'CO');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (788, 'Bantengan', 'ID');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (789, 'Guaíra', 'BR');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (790, 'Serawai', 'ID');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (791, 'Simnas', 'LT');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (792, 'Acandí', 'CO');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (793, 'Gur’yevsk', 'RU');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (794, 'Montague', 'CA');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (795, 'Beizheng', 'CN');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (796, 'Zhengyangshan', 'CN');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (797, 'Baja Mar', 'HN');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (798, 'Alenquer', 'PT');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (799, 'Berëzovka', 'RU');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (800, 'Vacaria', 'BR');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (801, 'Vërtop', 'AL');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (802, 'Rosthern', 'CA');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (803, 'Melaka', 'MY');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (804, 'Kombolcha', 'ET');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (805, 'Joaquín Suárez', 'UY');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (806, 'Ravne na Koroškem', 'SI');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (807, 'Perstorp', 'SE');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (808, 'Oakland', 'US');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (809, 'Pégeia', 'CY');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (810, 'Savannah', 'US');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (811, 'Pyongyang', 'KP');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (812, 'Murtajih', 'ID');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (813, 'Princeton', 'CA');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (814, 'Söderhamn', 'SE');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (815, 'Kunyang', 'CN');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (816, 'Pudoc', 'PH');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (817, 'Ostravice', 'CZ');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (818, 'Subusub', 'PH');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (819, 'Carvalhal', 'PT');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (820, 'Kelīshād va Sūdarjān', 'IR');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (821, 'Lishan', 'CN');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (822, 'Maqian', 'CN');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (823, 'Orekhovo-Borisovo', 'RU');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (824, 'Thul', 'PK');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (825, 'Fairview', 'IE');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (826, 'Itako', 'JP');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (827, 'København', 'DK');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (828, 'Bradashesh', 'AL');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (829, 'Strängnäs', 'SE');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (830, 'Xingbin', 'CN');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (831, 'Dourados', 'BR');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (832, 'Suwa', 'JP');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (833, 'Kalapagada', 'ID');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (834, 'Extremoz', 'BR');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (835, 'Tierp', 'SE');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (836, 'Ankazoabo', 'MG');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (837, 'Samran', 'TH');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (838, 'Berehomet', 'UA');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (839, 'Sulang Tengah', 'ID');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (840, 'Longtanhe', 'CN');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (841, 'Donggaocun', 'CN');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (842, 'Mazamet', 'FR');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (843, 'Kukurečani', 'MK');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (844, 'Baltimore', 'US');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (845, 'Xiayang', 'CN');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (846, 'Edson', 'CA');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (847, 'Fengjiang', 'CN');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (848, 'Yam', 'RU');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (849, 'Maardu', 'EE');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (850, 'Belén de los Andaquíes', 'CO');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (851, 'Tarata', 'BO');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (852, 'Zungeru', 'NG');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (853, 'Tha Yang', 'TH');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (854, 'Otan Aiyegbaju', 'NG');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (855, 'Or Yehuda', 'IL');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (856, 'Somdet', 'TH');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (857, 'Jiuzihe', 'CN');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (858, 'Pochep', 'RU');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (859, 'Xekar', 'CN');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (860, 'Narach', 'BY');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (861, 'Wujing', 'CN');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (862, 'Säter', 'SE');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (863, 'Monte Branco', 'PT');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (864, 'Thị Trấn Phong Thổ', 'VN');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (865, 'Mangai', 'CD');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (866, 'Meneou', 'CY');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (867, 'Dar es Salaam', 'TZ');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (868, 'Huliao', 'CN');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (869, 'Sipeng', 'CN');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (870, 'Miyakonojō', 'JP');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (871, 'Głowno', 'PL');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (872, 'Chalchuapa', 'SV');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (873, 'Shreveport', 'US');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (874, 'Nowosielce', 'PL');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (875, 'Zachepylivka', 'UA');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (876, 'Qindu', 'CN');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (877, 'Tuchola', 'PL');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (878, 'Stockholm', 'SE');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (879, 'Hanjiaji', 'CN');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (880, 'Hebi', 'CN');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (881, 'Xiaojinkou', 'CN');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (882, 'Linköping', 'SE');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (883, 'Oslomej', 'MK');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (884, 'Jialou', 'CN');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (885, 'Tanbu', 'CN');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (886, 'Krasnopillya', 'UA');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (887, 'Yandian', 'CN');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (888, 'Osiedle-Nowiny', 'PL');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (889, 'Loshnitsa', 'BY');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (890, 'Tembeling', 'ID');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (891, 'Villefranche-sur-Saône', 'FR');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (892, 'Tarbagatay', 'RU');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (893, 'Capioví', 'AR');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (894, 'Landim', 'PT');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (895, 'Aipe', 'CO');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (896, 'Barra Bonita', 'BR');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (897, 'Fornos de Algodres', 'PT');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (898, 'Dongshandi', 'CN');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (899, 'Carmen de Viboral', 'CO');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (900, 'Paiisa', 'PH');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (901, 'Zhenjiang', 'CN');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (902, 'Bābol', 'IR');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (903, 'Bhalwāl', 'PK');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (904, 'Huicheng', 'CN');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (905, 'Xuwei', 'CN');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (906, 'Jingxiyuan', 'CN');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (907, 'Hobart', 'AU');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (908, 'Kovernino', 'RU');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (909, 'Maykor', 'RU');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (910, 'Rāmganj', 'BD');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (911, 'Gaoxing', 'CN');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (912, 'Ambilobe', 'MG');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (913, 'Tëploye', 'RU');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (914, 'Venado Tuerto', 'AR');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (915, 'Soritor', 'PE');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (916, 'Novogurovskiy', 'RU');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (917, 'Nagasari', 'ID');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (918, 'Reiko', 'KR');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (919, 'Villa del Rosario', 'CO');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (920, 'Mersa Matruh', 'EG');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (921, 'Dulce Nombre', 'HN');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (922, 'Bestöbe', 'KZ');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (923, 'Karsin', 'PL');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (924, 'Hoima', 'UG');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (925, 'Varberg', 'SE');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (926, 'Sukakerta', 'ID');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (927, 'Cakungsari', 'ID');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (928, 'Effium', 'NG');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (929, 'Stari Grad', 'HR');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (930, 'Xincheng', 'CN');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (931, 'Wielbark', 'PL');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (932, 'Labé', 'GN');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (933, 'Pyapon', 'MM');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (934, 'Xishan', 'CN');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (935, 'Beipai', 'CN');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (936, 'Nantes', 'FR');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (937, 'Fengli', 'CN');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (938, 'Forquilhinha', 'BR');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (939, 'Arruda dos Vinhos', 'PT');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (940, 'Montrouge', 'FR');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (941, 'Serzedo', 'PT');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (942, 'Velikovechnoye', 'RU');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (943, 'Sumberejo', 'ID');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (944, 'Karangagung Timur', 'ID');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (945, 'Grenoble', 'FR');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (946, 'Bojonegoro', 'ID');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (947, 'Huangling', 'CN');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (948, 'Daja', 'ID');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (949, 'Mailsi', 'PK');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (950, 'Ciguha Tengah', 'ID');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (951, 'Banyo', 'CM');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (952, 'San Isidro', 'PE');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (953, 'Sara Kunda', 'GM');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (954, 'Igreja', 'PT');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (955, 'Benito Juarez', 'MX');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (956, 'Vilhena', 'BR');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (957, 'Washington', 'US');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (958, 'Ciénaga', 'CO');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (959, 'Dovhe', 'UA');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (960, 'Wróblew', 'PL');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (961, 'Guayabal', 'VE');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (962, 'Wentugaole', 'CN');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (963, 'Kelapa', 'ID');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (964, 'Atlanta', 'US');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (965, 'Shuiquan', 'CN');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (966, 'Banos', 'PH');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (967, 'Dobruševo', 'MK');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (968, 'Francisco Villa', 'MX');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (969, 'Guanzhuang', 'CN');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (970, 'Kamirenjaku', 'JP');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (971, 'Apuri', 'ID');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (972, 'Sobral', 'PT');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (973, 'Huangbei', 'CN');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (974, 'Pangpang', 'PH');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (975, 'Vetluga', 'RU');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (976, 'Gelsenkirchen', 'DE');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (977, 'Grębków', 'PL');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (978, 'San Vicente', 'CR');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (979, 'Santiago', 'PH');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (980, 'Xundian', 'CN');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (981, 'Huabu', 'CN');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (982, 'Dzikowiec', 'PL');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (983, 'Shijiao', 'CN');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (984, 'Landskrona', 'SE');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (985, 'San Juan', 'PH');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (986, 'Tosontsengel', 'MN');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (987, 'Tarakaniv', 'UA');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (988, 'Panite', 'ID');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (989, 'Robatal', 'ID');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (990, 'Cần Giờ', 'VN');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (991, 'Nantes', 'FR');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (992, 'Wanglian', 'CN');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (993, 'Orlando', 'US');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (994, 'Donostia-San Sebastian', 'ES');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (995, 'Cidikit Girang', 'ID');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (996, 'Karangboyo', 'ID');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (997, 'Pentre', 'GB');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (998, 'Dalong', 'ID');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (999, 'Rodionovo-Nesvetayskaya', 'RU');
insert into PAIS (ID, NOMBRE, ABREVIATURA) values (1000, 'Hengshanqiao', 'CN');
