CREATE TABLE IF NOT EXISTS ARBITRO(
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    FECHA_REGISTRO TIMESTAMP,
    MATERNO VARCHAR(255),
    NOMBRE VARCHAR(255),
    PATERNO VARCHAR(255),
    RUTA_FOTO VARCHAR(255),
    SEXO VARCHAR(255),
    ADMIN_ID VARCHAR(45) NOT NULL,
    GEOLOCATION_ID BIGINT NOT NULL
);