CREATE TABLE IF NOT EXISTS CANCHA (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    ADMIN_ID VARCHAR(25) NOT NULL,
    NOMBRE VARCHAR(50) NOT NULL,
    ALIAS VARCHAR(70) NOT NULL,
    DESCRIPCION VARCHAR(70) NOT NULL,
    GEOLOCATION_ID BIGINT NOT NULL
);