CREATE TABLE IF NOT EXISTS JUGADOR (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    ADMIN_ID VARCHAR(25) NOT NULL,
    NOMBRE VARCHAR(50) NOT NULL,
    PATERNO VARCHAR(70) NOT NULL,
    MATERNO VARCHAR(70) NOT NULL,
    RUTA_FOTO VARCHAR(70) NOT NULL,
    SEXO VARCHAR(70) NOT NULL,
    FECHA_REGISTRO TIMESTAMP NOT NULL,
    GEOLOCATION_ID BIGINT NOT NULL
);