CREATE TABLE IF NOT EXISTS LIGA (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE VARCHAR(50) NOT NULL,
    NOMBRE_COMPLETO VARCHAR(70) NOT NULL,
    TELEFONO VARCHAR(70) NOT NULL,
    GEOLOCATION_ID BIGINT NOT NULL,
    ADMIN_ID VARCHAR(25) NOT NULL
);