CREATE TABLE IF NOT EXISTS PARTIDO (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    JORNADA_ID BIGINT NOT NULL,
    LOCAL_ID BIGINT NOT NULL,
    PUNTOS_LOCAL BIGINT NOT NULL,
    VISITANTE_ID BIGINT NOT NULL,
    PUNTOS_VISITANTE BIGINT NOT NULL,
    CANCHA_ID BIGINT NOT NULL,
    HORARIO TIMESTAMP NOT NULL,
    STATUS VARCHAR(50) NOT NULL
);