CREATE TABLE IF NOT EXISTS TORNEO (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    LIGA_ID BIGINT NOT NULL,
    NOMBRE VARCHAR(50) NOT NULL,
    CLAVE VARCHAR(50) NOT NULL,
    DESCRIPCION VARCHAR(70) NOT NULL,
    FECHA_INICIO TIMESTAMP NOT NULL,
    FECHA_FIN TIMESTAMP NOT NULL,
    STATUS VARCHAR(10) NOT NULL
);