CREATE TABLE IF NOT EXISTS TORNEOJUGADOR (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    TORNEO_EQUIPO_ID BIGINT NOT NULL,
    JUGADOR_ID BIGINT NOT NULL,
    STATUS_JUGADOR VARCHAR(50) NOT NULL,
    POSICION_JUGADOR VARCHAR(50) NOT NULL,
    NUMERO VARCHAR(5) NOT NULL
);