CREATE TABLE IF NOT EXISTS GEOLOCATION (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    CALLE VARCHAR(50) NOT NULL,
    NO_EXTERIOR VARCHAR(70) NOT NULL,
    NO_INTERIOR VARCHAR(70) NULL,
    CODIGO_POSTAL VARCHAR(70) NOT NULL,
    COLONIA_ID BIGINT NOT NULL,
    LONGITUDE DOUBLE NULL,
    LATITUDE DOUBLE NULL
);

INSERT INTO GEOLOCATION (ID, CALLE, NO_EXTERIOR, NO_INTERIOR, CODIGO_POSTAL, COLONIA_ID, LONGITUDE, LATITUDE) VALUES
(1, 'Claro Tapia', '15', null, '42700', 1, 2234234, 2342343),
(2, 'Felipe Angeles', '478', null, '41458', 1, 2234234, 2342343);
