CREATE TABLE IF NOT EXISTS HOTEL(
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE_OFICIAL VARCHAR(100) NOT NULL,
    DIRECCION VARCHAR(100) NOT NULL,
    NO_EXT VARCHAR(25) NOT NULL,
    NO_INT VARCHAR(25) NOT NULL,
    COLONIA VARCHAR(100) NOT NULL,
    MUNICIPIO VARCHAR(100) NOT NULL,
    ESTADO VARCHAR(100) NOT NULL,
    PAIS VARCHAR(100) NOT NULL,
    FECHA_FUNDACION TIMESTAMP NOT NULL
);  

INSERT INTO HOTEL(ID, NOMBRE_OFICIAL, DIRECCION, NO_EXT, NO_INT, COLONIA, MUNICIPIO, ESTADO, PAIS, FECHA_FUNDACION) VALUES
(1, STRINGDECODE('Hotel M\u00e9xico'), 'Paseo de la Reforma', '255', 'PISO 2', 'Cuahutemoc', 'Cuahutemoc', 'Distrito Federal',
    STRINGDECODE('M\u00e9xico'), TIMESTAMP '2000-03-11 00:00:00.000'),
(2, STRINGDECODE('Hotel Posada'), 'Av Insurgentes', '15', 'PB', 'Col del Valle', 'Benito Juárez', 'Distrito Federal',
        STRINGDECODE('M\u00e9xico'), TIMESTAMP '2000-03-11 00:00:00.000');

CREATE TABLE IF NOT EXISTS HOTEL_CATEGORIA_SERVICIO(
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    CATEGORIA_ID BIGINT,
    SERVICIO_ID BIGINT,
    HOTEL_ID BIGINT
);

INSERT INTO HOTEL_CATEGORIA_SERVICIO(ID, CATEGORIA_ID, SERVICIO_ID, HOTEL_ID) VALUES
(1, 1, 1, 1),(2, 1, 2, 1),(3, 2, 3, 1),(4, 2, 4, 1),(5, 3, 5, 1),(6, 3, 6, 1);