CREATE TABLE IF NOT EXISTS JORNADA (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    TORNEO_ID BIGINT NOT NULL,
    NOMBRE VARCHAR(50) NOT NULL,
    FASE VARCHAR(50) NOT NULL
);

INSERT INTO JORNADA (ID, TORNEO_ID, NOMBRE, FASE) VALUES
(1, 1, 'Jornada 1', 'REGULAR'),
(2, 1, 'Jornada 2', 'REGULAR');