CREATE TABLE IF NOT EXISTS JUGADOR (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    ADMIN_ID VARCHAR(25) NOT NULL,
    NOMBRE VARCHAR(50) NOT NULL,
    PATERNO VARCHAR(70) NOT NULL,
    MATERNO VARCHAR(70) NOT NULL,
    RUTA_FOTO VARCHAR(70) NOT NULL,
    SEXO VARCHAR(70) NOT NULL,
    FECHA_REGISTRO TIMESTAMP NOT NULL,
    GEOLOCATION_ID BIGINT NOT NULL
);

INSERT INTO JUGADOR (ID, ADMIN_ID, NOMBRE, PATERNO, MATERNO, RUTA_FOTO, SEXO, FECHA_REGISTRO, GEOLOCATION_ID) VALUES
(1, 'jperez', 'Roberto Salvador', 'Olguin', 'Lozano', 'asdasd', 'MASCULINO', TIMESTAMP '2015-01-01 14:25:00.000', 1),
(2, 'jperez', 'Salvador Isaias', 'Garcia', 'Olguin', 'asdassd', 'MASCULINO', TIMESTAMP '2015-01-01 14:25:00.000', 2);
