CREATE TABLE IF NOT EXISTS TORNEOCANCHA (
    ID SERIAL PRIMARY KEY,
    TORNEO_ID BIGINT NOT NULL,
    CANCHA_ID BIGINT NOT NULL,
    STATUS_CANCHA VARCHAR(50) NOT NULL
);

INSERT INTO TORNEOCANCHA (ID, TORNEO_ID, CANCHA_ID, STATUS_CANCHA) VALUES
(1, 1, 1, 'INSCRITO'),
(2, 1, 2, 'INSCRITO');