CREATE TABLE IF NOT EXISTS TORNEO (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    LIGA_ID BIGINT NOT NULL,
    NOMBRE VARCHAR(50) NOT NULL,
    CLAVE VARCHAR(50) NOT NULL,
    DESCRIPCION VARCHAR(70) NOT NULL,
    FECHA_INICIO TIMESTAMP NOT NULL,
    FECHA_FIN TIMESTAMP NOT NULL,
    STATUS VARCHAR(10) NOT NULL
);

INSERT INTO TORNEO (ID, LIGA_ID, NOMBRE, CLAVE, DESCRIPCION, FECHA_INICIO, FECHA_FIN, STATUS) VALUES
(1, 1, 'Primera Fuerza Verano 2015', 'primera-fuerza-verano-2015', 'Enero a Junio 2015 Primer Fuerza', TIMESTAMP '2015-01-01 14:25:00.000', TIMESTAMP '2015-01-15 14:25:00.000', 'ENPROCESO');