CREATE TABLE IF NOT EXISTS GEOLOCATION (
    ID SERIAL PRIMARY KEY,
    CALLE VARCHAR(50) NOT NULL,
    NO_EXTERIOR VARCHAR(70) NOT NULL,
    NO_INTERIOR VARCHAR(70) NULL,
    COLONIA_ID BIGINT NOT NULL,
    LONGITUDE decimal NULL,
    LATITUDE decimal NULL
);

INSERT INTO GEOLOCATION (ID, CALLE, NO_EXTERIOR, NO_INTERIOR, COLONIA_ID, LONGITUDE, LATITUDE) VALUES
(1, 'Claro Tapia', '15', null, 1, 2234234, 2342343),
(2, 'Felipe Angeles', '478', null, 1, 2234234, 2342343);
