CREATE TABLE IF NOT EXISTS PARTIDO (
    ID SERIAL PRIMARY KEY,
    JORNADA_ID BIGINT NOT NULL,
    LOCAL_ID BIGINT NOT NULL,
    PUNTOS_LOCAL BIGINT NOT NULL,
    VISITANTE_ID BIGINT NOT NULL,
    PUNTOS_VISITANTE BIGINT NOT NULL,
    CANCHA_ID BIGINT NOT NULL,
    HORARIO TIMESTAMP NOT NULL,
    STATUS VARCHAR(50) NOT NULL
);

INSERT INTO PARTIDO (ID, JORNADA_ID, LOCAL_ID, PUNTOS_LOCAL, VISITANTE_ID, PUNTOS_VISITANTE, CANCHA_ID, HORARIO, STATUS) VALUES
(1, 1, 1, 0, 2, 0, 1, TIMESTAMP '2015-09-04 14:25:00.000', 'PROGRAMADO');