CREATE TABLE IF NOT EXISTS TORNEOEQUIPO (
    ID SERIAL PRIMARY KEY,
    TORNEO_ID BIGINT NOT NULL,
    EQUIPO_ID BIGINT NOT NULL,
    STATUS_EQUIPO VARCHAR(50) NOT NULL
);

INSERT INTO TORNEOEQUIPO (ID, TORNEO_ID, EQUIPO_ID, STATUS_EQUIPO) VALUES
(1, 1, 1, 'INSCRITO'),
(2, 1, 2, 'INSCRITO');